### ISSUE TITLE
Column width for query results

### ISSUE THREAD

**Issue by kschepperly** [MarkMpn/Sql4Cds#10]
Is it possible to set a default column width or expand all columns in the result pane without having to do it manually after each run? I often build a query and then refresh that query several times while making updates in  CRM. Currently all columns are very tight and data is truncated so i have to drag/expand each column one by one every time I reload.

![image](https://user-images.githubusercontent.com/29107670/86784690-ce93a580-c02f-11ea-8424-03bb451afb23.png)

**Comment by MarkMpn** [comment]
I originally had it auto-sizing columns, but it would hit performance problems if you ran queries like `SELECT * FROM contact` that brought back 200+ columns. I'll give it another go to see if anything's improved or if I can easily make it an option you can choose to turn on.

**Comment by MarkMpn** [comment]
Released in 2.2.0

**Comment by kschepperly** [comment]
Thanks Mark! I tested the enhancement in 2.2 and it works flawlessly. Greatly appreciated!
