### ISSUE TITLE
"CrmServiceClient.set_EnableAffinityCookie Method not found" Error on INSERT with v5.2.1

### ISSUE THREAD

**Issue by richwaring** [MarkMpn/Sql4Cds#102]
Previously, I could INSERT new rows using either a SELECT or VALUES keyword, as per the examples below, but with the new version today I'm getting the following...

    Method not found: 'Void Microsoft.Xrm.Tooling.Connector.CrmServiceClient.set_EnableAffinityCookie(Boolean)'.
    Method not found: 'Void Microsoft.Xrm.Tooling.Connector.CrmServiceClient.set_EnableAffinityCookie(Boolean)'.
    See the Execution Plan tab for details of where this error occurred

Example insert statements...

insert into sshared_order (sshared_name, sshared_deliverydate, sshared_client, sshared_contact)
select 'Calendar test order 4', '2021-08-15 09:00', sshared_client, sshared_contact
from sshared_order where sshared_orderid = 'bd9d4322-4c98-4ddb-a857-7a70b8337563'

insert into sshared_order (sshared_name, sshared_deliverydate, sshared_client, sshared_contact)
values ('Calendar test order 4', '2021-08-15 09:00', '38245f45-36ca-eb11-bacc-000d3a86e81e', '81202414-36ca-eb11-bacc-000d3a86e81e')

**Comment by MarkMpn** [comment]
It sounds like you might have an old version of XrmToolBox - can you use Help > Check for update? I'm currently on 1.2021.6.51

**Comment by richwaring** [comment]
Spot on - this is resolved for me now. Thanks, Mark :)
