### ISSUE TITLE
XRMToolbox Issue: Request keeps showing "Unknown column" in "SQL 4 CDS" tool

### ISSUE THREAD

**Issue by Jamal-kacemy** [MarkMpn/Sql4Cds#105]
Hi i am getting an error (Unknown column: cnt) while i was trying this sql request, but the variable is defined, i tried other implementations but it didn't work:

update contact 
SET myfield = 0
where contactid in 
(select contactid from contact 
where emailaddress1 in(select emailaddress1 from ( SELECT emailaddress1, COUNT(emailaddress1) as cnt
FROM contact
GROUP BY emailaddress1
HAVING cnt>1) as s))
any idea on what i am missing?

**Comment by MarkMpn** [comment]
I think there's just too many nested subqueries here for it to understand currently. You can simplify this query though to either a single subquery:

```sql
UPDATE contact
SET    myfield = 0
WHERE  emailaddress1 IN (SELECT   emailaddress1
                         FROM     contact
                         GROUP BY emailaddress1
                         HAVING   count(emailaddress1) > 1);
```

or a join:

```sql
UPDATE contact1
SET    myfield = 0
FROM   contact AS contact1
       INNER JOIN
       contact AS contact2
       ON contact1.emailaddress1 = contact2.emailaddress1
WHERE  contact1.contactid <> contact2.contactid;
```

Either of these should get you the same result.

**Comment by Jamal-kacemy** [comment]
Thank you @MarkMpn, the first request worked for me.
