### ISSUE TITLE
"Unable to Login to Dynamics CRM at McTools.Xrm.Connection..."

### ISSUE THREAD

**Issue by treesloth** [MarkMpn/Sql4Cds#116]
We're trying to set up a couple of users with Xrm and SQL 4 CDS.  When we create a connection and attempt to connection we get the following error (see also the attached image.  This could easily be an error on my part, as I am also a relatively new user of this fantastic tool.

![XrmConnectionError](https://user-images.githubusercontent.com/7399050/134963291-69822813-d2ba-462b-b059-b0c6f5bcbb79.jpg)

**Comment by MarkMpn** [comment]
I'd start off looking through the documentation for [Connecting to an environment with XrmToolBox](https://www.xrmtoolbox.com/documentation/for-users/connecting-to-an-organization/). This goes through the various different connection methods available - assuming your using D365 Online I'd suggest you use the OAuth/MFA or SDK Login Control methods.
