### ISSUE TITLE
Cannot update a custom entity - attempting to set "ContactId" throws exception

### ISSUE THREAD

**Issue by marcscheuner-bfh** [MarkMpn/Sql4Cds#126]
This looks a bit like issue #122 - but I tried all the things mentioned there, and they didn't work for me.

I have a bunch of custom entities - basically a "log" and a "contract" entity - and the contract has a link to a contact - property is called "ambcust_contactid" and it's a regular, normal, non-polymorphic entity reference.

Some of those contact ids were not set, and I'm trying to update them - using this SQL code in SQL-4-CDS v5.2.5 in the XrmToolBox:

```
update ambcust_matriculation
-- set ambcust_contactid = cast('8ca47da2-4115-ec11-b6e6-000d3add0174' as uniqueidentifier)
set ambcust_contactid = '8ca47da2-4115-ec11-b6e6-000d3add0174'
from ambcust_matriculation 
inner join bfh_systemlog sl on ambcust_matriculation.ambcust_matriculationid = sl.bfh_registration_id
inner join contact c on sl.bfh_person_number = c.ambcust_isapersonnumber
where (bunch of harmless conditions)
```

I tried with and without the "cast(..... as uniqueidentifier)", I tried with and without the "Use TDS endpoint if possible" option, I tried using a column (from the "bfh_systemlog" entity) or a hardcoded GUID string - in all scenarios, I keep getting this error:

_Sql error: Generic SQL error. CRM ErrorCode: -2147204784 Sql ErrorCode: -2146232060 Sql Number: 8169
Exception output:: System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting from a character string to uniqueidentifier._

Any further ideas? I tried in the TDS endpoint in SSMS as well - same error occurs, so I kinda believe it's not a SQL-4-CDS specific issue - but any idea on what's going on here?? Any way to get this to work properly?

**Comment by marcscheuner-bfh** [comment]
Could not reproduce anymore, after I modified the query a bit

**Comment by MarkMpn** [comment]
Can you try running it as a select statement, i.e.

```sql
select *
from ambcust_matriculation 
inner join bfh_systemlog sl on ambcust_matriculation.ambcust_matriculationid = sl.bfh_registration_id
inner join contact c on sl.bfh_person_number = c.ambcust_isapersonnumber
where (bunch of harmless conditions)
```

and see if you get the same error? My guess is that one of your joins or filter conditions is forcing a type conversion of string to guid where the string data can't be converted.
