### ISSUE TITLE
ImplicitTypeConversion test fails

### ISSUE THREAD

**Issue by miseeger** [MarkMpn/Sql4Cds#128]
I still see this annoying test fail for `ImplicitTypeConversion` test and I'm not able to track it down yet. Otherwise I would have created a pull request with my correction ... 👼🏼
![grafik](https://user-images.githubusercontent.com/1128963/143926582-c0b5abcf-5aec-449c-80e4-ebffb3212adf.png)

**Comment by MarkMpn** [comment]
I guess this is related to regional settings. Can you post a screenshot of your Windows regional songs (number formatting etc) and I'll see if I can reproduce it

**Comment by MarkMpn** [comment]
I think this is fixed in #129, can you pull that version and confirm this works for you?

**Comment by miseeger** [comment]
Yes, that fixed the problem. Thank you very much for this quick fix 👍🏼
