### ISSUE TITLE
Custom tables not selectable

### ISSUE THREAD

**Issue by mschaaks** [MarkMpn/Sql4Cds#136]
Hi @MarkMpn , first let me say this tool is incredibly valuable for me to assist in understanding what's going on in the Dataverse database while doing power platform development. I however cannot get my head around the following issue: how to query custom tables? I have checked all kinds of configuration elements (solution scope, table type, security configuration), but still i am not able to see the table appear in the SQL4CDS tool. Any ideas what is preventing me from querying the custom table ? Thanks a lot!

**Comment by MarkMpn** [comment]
There's nothing special you should need to do here, it should show all the tables including custom ones. The list of tables is loaded at the point you open the tool, so if you create a new one while the tool is open I wouldn't expect it to display. You can force it to reload the list of tables by right-clicking on the instance name in the Object Explorer pane and clicking Refresh. You might also want to double-check that you are connected to the instance you think you are - once you've got a query tab open, click the "Properties" tab on the right hand side to see the URL and some other details of the instance you are querying.

**Comment by mschaaks** [comment]
@MarkMpn : i tried different environments (default, developer, trial), refreshed and recreated connections, choosing different table options, but all actions with the same end result: the custom table does not show up in the tool. To be clear: i am creating the table with the Power App Maker portal. Could it be that some setting in the background is causing this issue ?

**Comment by MarkMpn** [comment]
Could you try deleting the files in your `%appdata%\MscrmTools\XrmToolBox\Metadata` folder and restart XrmToolBox and see if that allows it to get the new table?

**Comment by MarkMpn** [comment]
I'm closing this for now, please let me know if you still have the problem after clearing the metadata cache folder.
