### ISSUE TITLE
FIXED - Version 5.3.1.0 not showing links for GUIDS in the result set

### ISSUE THREAD

**Issue by beccalinder** [MarkMpn/Sql4Cds#146]
![SQL4CDS_RESULTSET](https://user-images.githubusercontent.com/97184290/148255845-37ad06c4-957b-45c9-aa1a-4d436919b182.jpg)

**Comment by MarkMpn** [comment]
I notice the TDS endpoint is enabled - in the Settings window, do you have the option enabled to use it when possible?

**Comment by beccalinder** [comment]
Like this?
![image](https://user-images.githubusercontent.com/97184290/148434270-6e10a1c9-0b80-4a7d-a25c-1182b0e3ecf6.png)

**Comment by MarkMpn** [comment]
Yes - with that option ticked, SQL 4 CDS only receives a simple guid value without the context of what it represents that's needed to create the link. With that option turned off you should get the links as expected. Can you let me know if that fixes it for you please?

**Comment by beccalinder** [comment]
That worked!  Thank you!
