### ISSUE TITLE
Error updating using datetime field

### ISSUE THREAD

**Issue by malam-dev** [MarkMpn/Sql4Cds#15]
Getting error:
Expression of type 'System.Nullable`1[System.DateTime]' cannot be used for return type 'System.Object'

update c set
po_lastactivitydate = ap.actualend
from contact c
join activitypointer ap on ap.regardingobjectid = c.contactid
  and ap.actualend is not null
where (c.po_lastactivitydate is null or ap.actualend > c.po_lastactivitydate)

Fields are regular Date/Time fields

**Comment by MarkMpn** [comment]
Thanks, this will be fixed in the next version
