### ISSUE TITLE
unable to run partitionby with plain select columns

### ISSUE THREAD

**Issue by ainsleybernard** [MarkMpn/Sql4Cds#150]
Hello 

I get an error when running the following sql, using version 5.4 sql4cds engine

```
SELECT accountid,
COUNT(accountid) OVER (PARTITION BY accountid ) AS test
FROM account
```
![image](https://user-images.githubusercontent.com/17305314/148837456-e0d3bd78-4c66-407c-bb64-ad6421dcd65d.png)

but this works perfectly
```

SELECT 
COUNT(accountid) OVER (PARTITION BY accountid ) AS test
FROM account
```

It seems like the code is seeing `COUNT` and assuming its an aggregate function like 
```

SELECT COUNT(accountid)
FROM account
GROUP BY accountid
```

Im not having the issue running it directly in SSMS using version 5.2.2

**Comment by MarkMpn** [comment]
Yes, window functions are not currently supported. It's something I'm investigating for a future version, but for the next update I'll look at making sure it generates an appropriate error when a window function is used.

**Comment by ainsleybernard** [comment]
alright sounds good thanks! Just curious will it make its way in near future or its some down the road. As its kind half working now. Just wondering if I can bank on it working sooner or later :)

**Comment by MarkMpn** [comment]
I can't guarantee anything, but it is supported by the TDS endpoint either in SSMS or SQL 4 CDS if you need it today.
