### ISSUE TITLE
SQL4CDS engine not using TDS endpoint when UseTDSEndpoint is set to true

### ISSUE THREAD

**Issue by ainsleybernard** [MarkMpn/Sql4Cds#151]
Hi, I am not sure if this a bug or not but when I set  `public bool UseTDSEndpoint => true;`
I expect to be able to run the following query in my c# project

```
SELECT accountid,
COUNT(accountid) OVER (PARTITION BY accountid ) AS test
FROM account
```

but Im getting the following error 
![image](https://user-images.githubusercontent.com/17305314/148974930-5acb5a04-ebd7-47a3-9e22-6ae568c13c07.png)

The above query functions runs in xrmtoolbox when I enable `use TDS Endpoint where possible (Preview)`
![image](https://user-images.githubusercontent.com/17305314/148974697-2d1124ff-ecf8-43da-8824-9b48c3532db1.png)

I'm I missing another option that needs to be enabled?

**Comment by ainsleybernard** [comment]
hmm, seems like the tds endpoint is not available, not sure why though, as it turned on in dynamics settings.

![image](https://user-images.githubusercontent.com/17305314/148984328-25a75fc2-2b99-419c-ab15-8fbc3d0e1f32.png)

**Comment by ainsleybernard** [comment]
ohhh I didnt notice it was a getter and setter, just had to set this

```
    var executionPlanBuilder = new ExecutionPlanBuilder(dataSources.Values, options);
    executionPlanBuilder.TDSEndpointAvailable = true;
```


Kind of misleading, as you would think the setting this option

`public bool UseTDSEndpoint => true
`

Would automatically set it, and if it couldnt because for example TDS is not enabled in dynamic environment  it would be false but with maybe a error message or something.

**Comment by MarkMpn** [comment]
Great, glad you got it working!
