### ISSUE TITLE
HINT for base entity in FetchXml

### ISSUE THREAD

**Issue by remyvd** [MarkMpn/Sql4Cds#155]
I have a query like:

    SELECT DISTINCT systemuserid, systemuser.fullname 
    FROM systemuser
    INNER JOIN account ON systemuser.systemuserid = account.ava_useridbezoekverantwoordelijkehore
    INNER JOIN contact ON account.primarycontactid = contact.contactid
    WHERE  account.statecode = 0 
    ...more filters

The generated FetchXml is like:

    <fetch xmlns:generator='MarkMpn.SQL4CDS'>
      <entity name='account'>
        <link-entity name='systemuser' to='ava_useridbezoekverantwoordelijkehore' from='systemuserid' alias='systemuser' link-type='inner'>
          <attribute name='systemuserid' />
      <attribute name='fullname' />
    </link-entity>
    <link-entity name='contact' to='primarycontactid' from='contactid' alias='contact' link-type='inner' />
    <filter>...<filter>
    </entity>
    </fetch>

While the FROM has systemuser as entity the FetchXml has account as baseentity. I assume it's for better performance, but I want to use this query in Power Automate and the systemuser needs to be the base entity for the retrieval.

Is there an table hint or other way I can force the base entity to be systemuser, even if the performance is wore?

**Comment by MarkMpn** [comment]
The tables are ordered this way in the FetchXML to avoid problems with paging. In some circumstances, having systemuser as the main entity might cause you to miss some records as you move on to later pages of the results. There's some more details on my blog at https://markcarrington.dev/2021/02/23/msdyn365-internals-paging-gotchas/#multiple_linked_entities

In short, there is no option in SQL 4 CDS to let you control the order of the entities in the generated FetchXML. I may look at a feature in FetchXML Builder though to allow you to quickly reorder the entities.

**Comment by remyvd** [comment]
Hi Mark, thanks for the quick response. I understand the problem and the optimalization to get reliable results back when doing paging.

But I don't think in this case it would result in the paging problem, because the returned rows are less than 50. I only need the systemusers that have any (one or more) accounts linked. I can even add a TOP 50 to the query to limit the results, to be safe.

But I understand it's better to be safe out of the box. Thanks for SQL4CDS, use it every day!
