### ISSUE TITLE
COUNT(*) does not work whereas COUNT(attributename) works

### ISSUE THREAD

**Issue by michalhainc** [MarkMpn/Sql4Cds#159]
Hello, thank you for great software. Helps a lot. 
Today I discovered that COUNT(*) is producing a 0 result but COUNT(attributename) works fine.

**Comment by MarkMpn** [comment]
Interesting - this seems to be working as expected for me.

Could you please post a screenshot of the execution plan it has used for the query when you get a 0 result? Click the ![image](https://user-images.githubusercontent.com/31017244/152514234-8b28c08e-a36c-4ab8-9172-b4ac97d9f23a.png) button in the toolbar and run the query again to get the Execution Plan tab next to the results.

Does this happen on all entity types or only specific ones?

**Comment by michalhainc** [comment]
Hello, here you are: 

![image](https://user-images.githubusercontent.com/3962233/152557480-69279046-2c90-4264-9e94-dab33cf1c0be.png)

execution plans: 
![image](https://user-images.githubusercontent.com/3962233/152557548-b2da2447-7f2e-4034-9749-f04ed438b4bc.png)

**Comment by MarkMpn** [comment]
Thanks - it's trying to use the [RetrieveTotalRecordCount](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/retrievetotalrecordcount?view=dynamics-ce-odata-9&WT.mc_id=DX-MVP-5004203) function to get the result of the `COUNT(*)` function quicker. However, the value returned by that function isn't live - it may have been calculated any time in the past 24 hours. If you've done a bulk load into the table it may still be returning the value from before that load, and it will catch up over the next day.

You can control this through the SQL 4 CDS settings - uncheck the "Use RetrieveTotalRecordCount request where possible" option. Your two queries should then produce the same execution plan and result.

I may change the default value of this setting in a future release.
