### ISSUE TITLE
Unsupport attribute type Owner for attribute ownerid

### ISSUE THREAD

**Issue by michaelmmcrae1** [MarkMpn/Sql4Cds#16]
```
UPDATE
account
SET
ownerid = 'b11ecdf7-4c05-ea11-813f-005056bd67bf'
WHERE
accountid = '65a95fcf-e343-ea11-8150-005056bd7a8f'

```
Both Id's are valid/actual records. First is a the Id of a User. 2nd is the Id of the Account.

This doesn't work and gives an error message that reads: "Unsupport attribute type Owner for attribute ownerid"

I have successfully updated Two Option fields. This is my first time trying to update a different data type.

**Comment by MarkMpn** [comment]
Thanks, this will be fixed in the next version.

**Comment by michaelmmcrae1** [comment]
@MarkMpn  thanks for confirming.

And thanks 10,000x for this tool!
