### ISSUE TITLE
Issue with tables having same Display Name but different schema names.

### ISSUE THREAD

**Issue by lshraybman** [MarkMpn/Sql4Cds#165]
In my instance we have two tables with Display name "Message" and different schema names: one is LI_MESSAGE and another NFC_MESSAGE. The tool displays doubles for each of those tables and gives an error when trying to query one of them.
![SQL4CDS-Error](https://user-images.githubusercontent.com/31146947/155582397-d716cd78-4a1a-45f3-b287-5e0e1a6ce09d.PNG)
![SQL4CDS-1](https://user-images.githubusercontent.com/31146947/155582689-6c2a28c1-867a-4c7a-8ee6-fbcbcdd40aaf.PNG)
![SQL4CDS-2](https://user-images.githubusercontent.com/31146947/155582691-11372f40-5ef2-4d89-8750-14ecea262a7c.PNG)

**Comment by MarkMpn** [comment]
Can you try the steps from #138 please?

**Comment by lshraybman** [comment]
Mark, thanks a lot, it worked.
