### ISSUE TITLE
issue with casting from `SqlString` to `SqlGuid` during execution of query

### ISSUE THREAD

**Issue by rafek1241** [MarkMpn/Sql4Cds#166]
**issue:** 
Query:
```
select top 10 * from aaduser 
```

Result:
```
Nie można przekonwertować obiektu typu 'System.Data.SqlTypes.SqlString' na obiekt typu 'System.Data.SqlTypes.SqlGuid'.Nie można przechowywać <0000000-....-0000000> w kolumnie id. Oczekiwanym typ to SqlGuid.
Nie można przekonwertować obiektu typu 'System.Data.SqlTypes.SqlString' na obiekt typu 'System.Data.SqlTypes.SqlGuid'.
```

It's in polish but I didn't set it up. It describes that there is an issue with casting from `SqlString` to `SqlGuid`.

**Comment by rafek1241** [comment]
Thank you for your explanation! It would be great to have different error message that is more meaningful.

**Comment by MarkMpn** [comment]
Just been testing this in my current dev version and it does coincidentally work if you do a simple `SELECT TOP 10 * FROM aaduser`. However, you'll still get some variant of the error `Specified cast is not valid.` if you try to do anything else with the `id` column other than just display it.

It also highlights another error with this virtual table provider that it does not honour the `TOP` clause and returns a full page of records regardless of how many you ask for in the FetchXML. Again, this would need a fix from Microsoft to resolve.
