### ISSUE TITLE
Order by boolean desc does not work

### ISSUE THREAD

**Issue by SolidSoils** [MarkMpn/Sql4Cds#169]
When ordering by multiple columns combined with a boolean field with option `DESC`, the table is not ordered by the boolean field.

**Comment by MarkMpn** [comment]
This seems to work for me:

```sql
SELECT   TOP 10 donotbulkemail,
                donotemail
FROM     account
ORDER BY donotbulkemail DESC, donotemail DESC;
```

With one record having both these fields set to true, one with only `donotbulkemail` set to true, one with only `donotemail` set to true and all the other records having both fields set to false, I get the expected results:

![image](https://user-images.githubusercontent.com/31017244/158452305-f96fc5a7-454d-4da5-a68e-fff4174dce22.png)

This is consistent with the results for the same query from the TDS endpoint.

Can you share a sample query where you're getting the wrong results please?

**Comment by MarkMpn** [comment]
I'm closing this for now, please reopen it if you have an example you can share that demonstrates the problem.
