### ISSUE TITLE
Incorrect case of Update column does not actually send column to Dataverse

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/Sql4Cds#170]
Was attempting to run this query to enable all plugin streps for my assembly and got an error that statuscode 1 is invalid for state code 1

```
UPDATE sdkmessageprocessingstep
SET Statecode = 0, statuscode = 1 
WHERE sdkmessageprocessingstepid in (
    SELECT step.sdkmessageprocessingstepid FROM sdkmessageprocessingstep step
    INNER JOIN plugintype ON step.eventhandler = plugintype.plugintypeid
    WHERE pluginType.name like 'MyPrefix.%' AND Statecode = 1
)
```

Finally figured out that if I made "Statecode" "statecode" it worked fine.  Looking at the fiddler, it we never adding "statecode" to the attributes to update and thus no update was actually being performed.

---
- Deployment: Online
- DB Version: 9.2.22022.137
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2022.2.54
- Tool Version: 5.4.1.0

**Comment by MarkMpn** [comment]
Fixed in 5983b11905fdcd058b7c452b3269d2e5ef6ef2d0
