### ISSUE TITLE
Select Count(*) Looks to only work for my own records?

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/Sql4Cds#179]
![image](https://user-images.githubusercontent.com/9728423/163271036-b2188eda-4c43-4892-a4dc-1a8ffef7a879.png)

---
- Deployment: Online
- DB Version: 9.2.22031.144
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2022.2.54
- Tool Version: 6.0.0.0

**Comment by MarkMpn** [comment]
Can you check if you have the "Use RetrieveTotalRecordCount request where possible" option enabled in the Settings dialog please? If so, please try disabling it - I'm going to remove this option in the next update as it produces incorrect results too often.

See also #159

**Comment by daryllabar** [comment]
Removing that fixed the count issue.

**Comment by MarkMpn** [comment]
Great - stick with that for the moment, the next version will force that option off by default but let you use a query hint to turn it back on if you _really_ need it
