### ISSUE TITLE
Error during query

### ISSUE THREAD

**Issue by msambhu** [MarkMpn/Sql4Cds#186]
The following query works with no issues:
```
select top 100 *
from account a
```

The following throws an "Object reference not set to an instance of an object." error.
```
select top 100 a.*
from account a
```

---
- Deployment: Online
- DB Version: 9.2.22032.150
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2022.2.54
- Tool Version: 6.0.1.0

**Comment by MarkMpn** [comment]
Duplicate of #183, already fixed for next version
