### ISSUE TITLE
Multiple Message Boxes Appearing when Executing Queries

### ISSUE THREAD

**Issue by jb-impact** [MarkMpn/Sql4Cds#191]
The number of message boxes like the one shown:
![image](https://user-images.githubusercontent.com/104577666/165775795-1127e0e6-e572-4975-8459-4472b8372d0f.png)
appear linearly with the number of times a query is executed. If I were to execute this query again, I would have to click `Yes` on two message boxes. Three times if I executed it once more. Most likely the message boxes are being consumed from a list but not deleted, so they accumulate for each press. This number is per tab, so making a new tab resets the count which I have been using as a temporary workaround.

Note that changing the query in the tab still causes multiple message boxes to appear. Executing queries that don't cause a message box (i.e. a SELECT statement) still increase the message box count by one when a query that DOES cause a message box finally executes.

Steps to reproduce:
1. Execute a query that will cause a warning message box based on your settings.
2. Execute it again
3. Keep executing it and you will quickly see the issue

**Comment by MarkMpn** [comment]
Thanks - I've got a fix ready for this, it'll be sorted in the next update.

**Comment by sybaris** [comment]
Thanks. Is it possible to make a new release to get this bug fixed in the latest version please ?
Thanks.

**Comment by MarkMpn** [comment]
I'm still testing some other changes, hoping to get a new release out this week
