### ISSUE TITLE
Confirmation on delete gets stuck infinitely re-prompting regardless of response

### ISSUE THREAD

**Issue by mark-smarthome** [MarkMpn/Sql4Cds#194]
Since upgrading, having the issue as folllows:
- write a delete statement, such as: delete from tableA where Field1 = 'whatever'
- when extecuted, it prompts asking if it should delete 1 record (typically just deleting one row).
- whether I click Yes or No, it continually re-prompts and there appears to be no way to get out of the prompt other thank killing the process
- the record is never deleted

Obviously, I can set the warning threshold higher for deleting records, which does allow it to work normally, but this worked fine before I recently updated.

---
- Deployment: Online
- DB Version: 9.2.22043.131
- Connection Controls Version: 1.2022.4.49
- XrmToolBox Version: 1.2022.2.54
- Tool Version: 6.0.1.0

**Comment by MarkMpn** [comment]
Can you please check if this is the same issue as #191 or something different?

**Comment by mark-smarthome** [comment]
Yes, it does look to be a duplicate of that issue.  After retrying the repro, i do see the same increasing number of prompts as I execute more queries then perform deletes.   I'll close this as a duplicate.

**Comment by mark-smarthome** [comment]
Duplicate of issue h #191.
