### ISSUE TITLE
[Suggestion] Add documentation for usage of Sql4Cds.Engine.

### ISSUE THREAD

**Issue by rafek1241** [MarkMpn/Sql4Cds#20]
Add documentation for usage of Sql4Cds.Engine with examples. ~~Honestly I'm not sure if that is production-ready.~~

**Comment by MarkMpn** [comment]
Do you have any particular concern that makes you think it’s not production ready?

**Comment by rafek1241** [comment]
My concerns are only from XRMToolset. I didn't use the engine so I can't say. I will strikethrough this opinion.

**Comment by MarkMpn** [comment]
I've added some initial documentation to the project and NuGet package readme files. More details to follow in the wiki.
