### ISSUE TITLE
Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by mark-santiago** [MarkMpn/Sql4Cds#203]
using the following

```sql
DECLARE @test = INT
SET @test = (SELECT count(*) FROM contact WHERE statecodename = 'active')
```

Error:
Value cannot be null.
Parameter name: source

SQL4CDS v6.1
XrmToolboxVersion : v1.2022.4.55

**Comment by MarkMpn** [comment]
Thanks, this will be fixed in the next update. As a workaround for now you can use:

```sql
DECLARE @test INT
SELECT @test = count(*) FROM contact WHERE statecodename = 'active'
```
