### ISSUE TITLE
Issue with query

### ISSUE THREAD

**Issue by mattybeard** [MarkMpn/Sql4Cds#204]
Just has an issue running the following query:

```
SELECT xxxx_invoicetype, xxxx_invoicetypename, COUNT(*)
FROM invoice i
inner join invoicedetail id on i.invoiceid = id.invoiceid
where id.productid = 'dbed7f15-7b12-e011-b981-00155d007501'
group by xxxx_invoicetype, xxxx_invoicetypename
```

I enabled TDS endpoint and it ran that way - but thought it may be worth flagging.

Error received was: `Sequence contains no elements`

**Comment by MarkMpn** [comment]
Thanks - there's some weird metadata breaking this. Fix coming shortly...

**Comment by AryScotto** [comment]
Hi Mark, Could you help me, about a problem in the SQL CDS installed in XRMToolBox, this is: 
1. After I installed version 6.1.0 of the SQL CDS in XRMToolBox, a simple Query stopped working and shows me the message: **String contains no elements** 
2. The query is SELECT top 10 salesorderdetailid FROM salesorderdetail 
3. The previous version works fine, is it possible for me to go back to the previous version in XRMToolBox, how can I do this.

**Comment by MarkMpn** [comment]
All previous releases are available to download from https://github.com/MarkMpn/Sql4Cds/releases. Get the MarkMpn.SQL4CDS.<version>.nupkg file and rename it to a .zip file. Copy the MarkMpn.SQL4CDS.dll file from within the lib\net462 folder to your XrmToolBox plugin folder, overwriting the version you already have (XrmToolBox needs to be closed to overwrite the file).
