### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by luckylachance** [MarkMpn/Sql4Cds#206]
SELECT Top 10 *
FROM   audit;

Hi Mark,
     I have run into a glitch with SQL 4 CDS 6.1.  I had an audit table query that worked fine in previous version.  And suddenly every query against the audit table returns "Sequence contains no elements"
     

![SQL4CDS](https://user-images.githubusercontent.com/22461750/169091799-8c44b9df-72d6-4cbc-ad6c-d2f24b8bcf4c.JPG)

**Comment by MarkMpn** [comment]
Duplicate of #204
