### ISSUE TITLE
[Suggestion] Update Activity Party Column

### ISSUE THREAD

**Issue by LinnZawWin** [MarkMpn/Sql4Cds#209]
By any chance, would it be easy to implement updating the Activity Party column (at least for a single value)
The scenario is to bulk update the Email sender to a particular queue.

`UPDATE email SET [from] = 'd79e8249-51ef-eb11-94ef-00224814e167', fromtype = 'queue' WHERE statecode = 0`

If it would be too complicated to implement, please feel free to Close this one without any action.

**Comment by MarkMpn** [comment]
I've been using a few queries lately to update activity parties - you can do it using a comma-separated list of values in the syntax `<logicalname>:<id>`, e.g.

```sql
UPDATE email SET [from] = 'queue:d79e8249-51ef-eb11-94ef-00224814e167' WHERE statecode = 0
```

You can also use this same logic to edit the values that are already in the activity party columns by using standard string manipulation functions to add or remove items from the string.
