### ISSUE TITLE
Bulk update auto number field possible?

### ISSUE THREAD

**Issue by tmykhaylovsky** [MarkMpn/Sql4Cds#216]
Hi Mark, thank you so much for this tool. As a dev, I use it daily for quick queries. Very helpful.

We have a case where we recently introduced an auto number. We need to backfill leads that don't have that auto generated number. Any chance it's possible via a SQL statement?

Here's the auto number formula: L{RANDSTRING:4}{RANDSTRING:4}

I am not able to get this tool to work: (will reach out to them separately)
https://www.xrmtoolbox.com/plugins/Sdmsols.XTB.AutoNumberUpdater/

Again, thank you for creating Sql4Cds. An absolutely unit of a tool :)

**Comment by MarkMpn** [comment]
Interesting! There isn't a function to generate a random string, but you could use the guid or created date as a source of randomness. It looks like you want 8 random characters so you could try something like:

UPDATE lead
SET new_autonumber = 'L' + LEFT(leadid, 8)
WHERE new_autonumber IS NULL

There's no guarantee that the first 8 characters of the guid will be unique in your data though, but this might give you a good start.
