### ISSUE TITLE
New Queries Saved somewhere?

### ISSUE THREAD

**Issue by tshelbourn** [MarkMpn/Sql4Cds#220]
More of a question than an issue let me know if there is a better place to ask.  When opening a new query tab is a file saved somewhere even if I did not save it my self?  In other words I created a query and didn't do a save and the tab disappeared when I connected to a different environment and the work is gone completely my fault but if a temp file exists somewhere that would be great. 

![image](https://user-images.githubusercontent.com/107878276/174648257-ad79488f-b476-4b37-8fbc-29c0ecfcb583.png)

**Comment by MarkMpn** [comment]
They're not saved as individual files. However, if you have the "Remember session details" option selected in the Settings dialog it should re-open with the same tabs as when you last closed it.
