### ISSUE TITLE
Update query failing on unique column as filter

### ISSUE THREAD

**Issue by mschaaks** [MarkMpn/Sql4Cds#221]
Running version 6.2.1 we get an execution error when updating records using the unique id column of a table as the filter.

update table
set field-to-update= 'x'
where unique-id-column = 'y'

error shown:

Unknown column: Expr1
See the Execution Plan tab for details of where this error occurred

**Comment by MarkMpn** [comment]
I believe this issue is fixed in 6.3.0 - if it's still failing can you give me a full example please?

**Comment by MarkMpn** [comment]
I'm closing this issue now, but please re-open it if it's still a problem.
