### ISSUE TITLE
[BUG] "NOT EXISTS" not working correct

### ISSUE THREAD

**Issue by diet3rix** [MarkMpn/Sql4Cds#230]
Awesome tool! When I just wanted to try the first statement with SubQuery, I noticed that "NOT EXISTS" does not work. It behaves like "EXISTS". The "NOT" seems to be ignored. Can this be improved?

**Comment by MarkMpn** [comment]
Could you post an example query with this problem please? My tests on this so far seem to be working as expected.

**Comment by diet3rix** [comment]
Sorry for the late response. To make it easier to reproduce, you can use the following ConnectionString: 
`AuthType=OAuth;Url=https://org632d8baa.crm4.dynamics.com/;Username=alans@CRM832769.OnMicrosoft.com;ClientId={51f81489-12ee-4a9e-aaae-a2591f45987d};LoginPrompt=Auto;RedirectUri=app://58145b91-0c36-4500-8554-080854f2ac97/`

Password: Wuh71087

SQL Statement:
`SELECT contact.fullname
FROM   contact
       INNER JOIN
       new_new_features_contact
       ON contact.contactid = new_new_features_contact.contactid
       INNER JOIN
       new_features
       ON new_new_features_contact.new_featuresid = new_features.new_featuresid
          AND new_features.new_name IN ('01', '02')
WHERE  NOT EXISTS (SELECT TOP 1 1
                   FROM   new_new_features_contact
                          INNER JOIN
                          new_features
                          ON new_new_features_contact.new_featuresid = new_features.new_featuresid
                             AND new_features.new_name IN ('N01', 'N02')
                   WHERE  new_new_features_contact.contactid = contact.contactid);`

I also noticed a difference. When I use the TDS endpoint, the result is correct. If I disable the option, I have the incorrect result.

Feel free to let me know if you need more information.

**Comment by MarkMpn** [comment]
Thanks, that's very helpful. I think I've isolated the problem to the Index Spool operator used to improve the efficiency of the query. For this small dataset you should get the expected results by adding the `OPTION (NO_PERFORMANCE_SPOOL)` query hint, but that won't give workable performance on a real-world dataset. For a larger dataset you can also work around the problem by explicitly converting the type of the `contact.contactid` column in the `WHERE` clause:

```sql
SELECT contact.fullname
FROM   contact
       INNER JOIN
       new_new_features_contact
       ON contact.contactid = new_new_features_contact.contactid
       INNER JOIN
       new_features
       ON new_new_features_contact.new_featuresid = new_features.new_featuresid
          AND new_features.new_name IN ('01', '02')
WHERE  NOT EXISTS (SELECT TOP 1 1
                   FROM   new_new_features_contact
                          INNER JOIN
                          new_features
                          ON new_new_features_contact.new_featuresid = new_features.new_featuresid
                             AND new_features.new_name IN ('N01', 'N02')
                   WHERE  new_new_features_contact.contactid = CONVERT (UNIQUEIDENTIFIER, contact.contactid));
```

I'll work on a proper fix for the next release.
