### ISSUE TITLE
[Suggestion] Support for subquerys

### ISSUE THREAD

**Issue by JaKovac87** [MarkMpn/Sql4Cds#235]
Support for subquerys would be really great.
Here is an example, i get error when trying to convert to xml, because the subquery

```sql
SELECT DISTINCT 
c.contactid,
aacc1.contactid,
aacc1.aa_contactcategoryid,
fullname
FROM   contact AS c
       LEFT OUTER JOIN
       aa_aa_contactcategory_contact AS aacc1
       ON c.contactid = aacc1.contactid
WHERE  c.aa_allowsurvey = 1
       AND parentcustomerid IS NOT NULL
       AND statecode = 0
       AND c.contactid NOT IN  (SELECT c.contactid
                               FROM   contact AS c
                                      LEFT OUTER JOIN
                                      aa_aa_contactcategory_contact AS aacc
                                      ON c.contactid = aacc.contactid
                               WHERE  aacc.aa_contactcategoryid = '222aab13-7aec-ec11-bb3d-6045bd8b41d9')
```

**Comment by MarkMpn** [comment]
I've tried running a version of this using the entities available in my test environment and it works as expected. Can you share the details of the error you get please?

I think you could also get the expected results by rewriting your query as:

```sql
SELECT DISTINCT c.contactid,
                aacc1.contactid,
                aacc1.aa_contactcategoryid,
                fullname
FROM   contact AS c
       LEFT OUTER JOIN
       aa_aa_contactcategory_contact AS aacc1
       ON c.contactid = aacc1.contactid
       LEFT OUTER JOIN
       aa_aa_contactcategory_contact AS aacc
       ON c.contactid = aacc.contactid
          AND aacc.aa_contactcategoryid = '222aab13-7aec-ec11-bb3d-6045bd8b41d9'
WHERE  c.aa_allowsurvey = 1
       AND parentcustomerid IS NOT NULL
       AND statecode = 0
       AND aacc.contactid IS NULL;
```

**Comment by JaKovac87** [comment]
Sorry @MarkMpn  i was abit unclear. Is there any way we write an query with an subquery in it, that it can convert that into an fetch xml? It was here i got stuck. The SQL worked fine, it was the convert to fetch that dident work.

But you made it work for me writing it without subguery and it works like an charm. Cheers mate

**Comment by MarkMpn** [comment]
Thanks, I'll check this out. There is some limited support for subqueries in FetchXML, but it allows you to do IN/EXISTS only and doesn't support NOT IN/NOT EXISTS. There's some information on my blog at https://markcarrington.dev/2020/04/05/inside-fetchxml-pt-10-link-entity-again/
