### ISSUE TITLE
Group-By query can't be processed by SQL-4-CDS

### ISSUE THREAD

**Issue by marcscheuner-bfh** [MarkMpn/Sql4Cds#237]
Hey Mark - why can't this GROUP BY query be successfully processed and executed by SQL-4-CDS ? 

```
select 
    year(createdon), count(*)
from
    bfh_researchproject
group by
    year(createdOn)
```

When I run it from SSMS with the TDS endpoint enabled, it works just fine and returns the expected results - number of research projects created by YEAR they were created in - seems harmless enough :-) 

But I only get an error from SQL-4-CDS:

**Column is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause: createdon**

Using SQL-4-CDS v6.4.0.0 inside the XrmToolbox.

**Comment by MarkMpn** [comment]
Looks like a case-sensitivity problem - I'll check it out for the next update, but for now just change the `createdOn` to `createdon` in the `GROUP BY` clause.
