### ISSUE TITLE
Error with some aggregates using SQL endpoint

### ISSUE THREAD

**Issue by malam-dev** [MarkMpn/Sql4Cds#24]
Example:

    select count(*) from phonecall where sortdate is null

Gives this error:

Invalid column name 'activityid_count'.
RequestId: TDS;5d0ef58c-4ab6-4195-8019-76da14b20334;3
Time: 2020-09-14T15:25:29.3166290Z

Issue in newest version (2.3.0)

**Comment by MarkMpn** [comment]
Thanks, this will be fixed in the next release.
