### ISSUE TITLE
Aggregate functions no longer work in v7.0.0

### ISSUE THREAD

**Issue by ethan-lynch** [MarkMpn/Sql4Cds#245]
Since upgrading to v7.0.0 basic aggregate queries have stopped working.

Example
`SELECT columnA, SUM(columnB) FROM table GROUP BY columnA`

Returns
Unknown Column: columnB

This works in v6.4.0.0

**Comment by MarkMpn** [comment]
This should be fixed in 7.0.1, please reopen if you still get the error.
