### ISSUE TITLE
Unable to do arithmetic (for inserts/updates/selects) on Money fields in CRM

### ISSUE THREAD

**Issue by malam-dev** [MarkMpn/Sql4Cds#25]
Example:

    update new_entity set new_money1 = new_money1 / 2.00 where new_name = 'test'

The binary operator Divide is not defined for the types 'System.Nullable`1[System.Decimal]' and 'System.Decimal'.

Similar error when using ints as well

**Comment by MarkMpn** [comment]
Thanks, this will be fixed in the next release.
