### ISSUE TITLE
Can't open after update 

### ISSUE THREAD

**Issue by jxs0900** [MarkMpn/Sql4Cds#250]
![image](https://user-images.githubusercontent.com/8445048/192824814-4c847aff-9744-4eed-a287-46a5ce4a2109.png)

After updating today I started getting this error when I try to open Sql4Cds.

**Comment by MarkMpn** [comment]
What version of Dynamics are you connecting to?

**Comment by jxs0900** [comment]
We're still on CRM 2013 :(

**Comment by MarkMpn** [comment]
I don't have an instance of CRM 2013 to test this against, but I think the next update should resolve this.

**Comment by jxs0900** [comment]
The update appears to have fixed my issue.  Thank you very much!!
