### ISSUE TITLE
Query with left joins fails after installing 7.0.0.0

### ISSUE THREAD

**Issue by tmykhaylovskyy** [MarkMpn/Sql4Cds#251]
Hi Mark, thanks for for creating this tool. I find myself spending a quarter of my days writing queries that will be used as fetchxml, testing, validation, etc,. Really a gem.

Here's a query that worked before installing 7.0.0.0

```sql
select a.svrs_customerid, count(ca.createdon), count(sn.createdon)
from account a
left join msdyn_customerasset ca ON a.accountid = ca.msdyn_account
left join jt_serialnumber sn ON sn.jt_customerasset = ca.msdyn_customerassetid and sn.statuscodename = 'Associated'
where a.svrs_customerid in (
...
)
and a.statecodename = 'Active' and ca.statecodename = 'Active'
group by a.svrs_customerid
having count(sn.createdon) = 0
```

Now, I get the following error:

```
An attribute can not be requested when an aggregate operation has been specified and its neither groupby nor aggregate.  NodeXml : <attribute name="accountid" />
```

If I remove the 2 left joins, the query works, but returns 0 results.

If I add a.accountid into the group by, a similar error occurs, but for msdyn_customerassetid, then for jt_serialnumberid, and that's where I paused.

If I keep adding columns to the group by, the meaning of aggregation is lost.

Mark, any advice would be appreciated!

**Comment by MarkMpn** [comment]
Thanks for the details, this should be fixed in the next update which I'll try to release shortly.

**Comment by tmykhaylovskyy** [comment]
Take your time and thank you!
