### ISSUE TITLE
Date format error

### ISSUE THREAD

**Issue by MarkMpn** [MarkMpn/Sql4Cds#257]
```sql
declare @dateFrom as Date;
set @dateFrom = ‘2022-09-29’;
select count(*) from contact c where c.modifiedon >= @dateFrom
```

gives:

```
The date-time format for MarkMpn.Sql4Cds.Engine.SqlDate is invalid, or value is outside the supported range
```

**Comment by sulimanbenhalim** [comment]
I have tried the following and it worked for me

`declare @dateFrom as Date = ‘20220929’
select count(*) from contact c where cast(c.modifiedon as date) >= @dateFrom`

**Comment by MarkMpn** [comment]
This should now work in 7.0.3, please reopen if you still have the problem. Using the first version of the query without the `CAST` should be much more efficient for large data sets.

**Comment by sulimanbenhalim** [comment]
Great work!
