### ISSUE TITLE
[Suggestion] Be able to do some string manipulations for updates/inserts

### ISSUE THREAD

**Issue by malam-dev** [MarkMpn/Sql4Cds#26]
TRIM, LTRIM, RTRIM, SUBSTRING, LEN, REPLACE would be helpful.

Examples:

    --extra spaces in data
    update contact set
    firstname = TRIM(firstname)
    where firstname like ' %' or firstname like '% '

    --leading zeros in data
    update contact set
    new_id = SUBSTRING(new_id, 2, LEN(new_id) - 1)
    where new_id like '0%'

    --replace emails after domain change
    update contact set
    emailaddress1 = REPLACE(emailaddress1, '@oldcompany.com', '@newcompany.com')
    where emailaddress1 like '%@oldcompany.com'

**Comment by MarkMpn** [comment]
REPLACE should already work in the latest version, I’ll look at adding the others

**Comment by MarkMpn** [comment]
I've included these extra functions now, this will be in the next release
