### ISSUE TITLE
FORMAT Function

### ISSUE THREAD

**Issue by sulimanbenhalim** [MarkMpn/Sql4Cds#260]
This is not an issue with the current version more than it's a missing feature

FORMAT function is not available in SQL 4 CDS

`Unknown function: FORMAT(suser.createdon, 'dd MMM yyyy') `

**Comment by MarkMpn** [comment]
I'd never actually noticed that function before, definitely looks useful! I'll look at adding this in a future update. In the meantime you might be able to get the result you want using `CONVERT` instead, e.g.

`CONVERT(VARCHAR(11), suser.createdon, 106)`

**Comment by sulimanbenhalim** [comment]
Thank you for the reply.
We look forward to the new version, and will take a look into the script you provided.
Best of luck!
