### ISSUE TITLE
on-or-after translates into = onorafter

### ISSUE THREAD

**Issue by bwmodular** [MarkMpn/Sql4Cds#261]
Really trivial issue but might be a trivial fix too :-)

If you have a query like this in fetchXmlBuilder, using on-or-after or on-or-before:
```
<fetch top='50'>
  <entity name='contact'>
    <filter>
      <condition attribute='createdon' operator='on-or-after' value='01-01-2022' />
    </filter>
  </entity>
</fetch>
```
and press 'Edit in SQL 4 CDS'
it 'translates' it to this:
```
SELECT TOP 50 
FROM   contact
WHERE  createdon = onorafter('01-01-2022')
```
which is not valid SQL syntax.

It's obviously very easy for me to edit the SQL so not a high priority.

Thanks as ever for general awesomeness of Sql4Cds

**Comment by MarkMpn** [comment]
Thanks for letting me know! I'm not sure why it hasn't added any columns to the SELECT clause, I'll look into that for a future update.

SQL 4 CDS handles these special FetchXML filter operators as custom functions like this to allow round-tripping between the FetchXML and SQL. It will handle executing that query by internally converting it back to the original FetchXML, but you can't execute it against the TDS endpoint.

If you want a more native SQL conversion, in SQL 4 CDS click Settings, go to the Conversion tab and select the "generate full SQL used by the server" option.

There are some more conversion options behind the scenes which I might expose in the next update too.
