### ISSUE TITLE
SQL 4 CDS SSMS installation

### ISSUE THREAD

**Issue by EldonKlaassen** [MarkMpn/Sql4Cds#262]
I have successfully downloaded SQL 4 CDS; I am able to use it to update Dataverse. 

I have also loaded the SSMS version.  However, when running MarkMpn.Sql4Cds.SSMS.Setup the installation wizard immediately returns "SQL 4 CDS - SSMS Edition Setup Wizard ended prematurely."  with additional text "SQL 4 CDS Edition Setup Wizard ended prematurely because of an error.  Your system has not been modified."

Can you help me correct this?

**Comment by MarkMpn** [comment]
Can you please get a log file of the installation so we can try to see what's going wrong? You should be able to get this by using the following command to run the installer:

```
msiexec /i MarkMpn.Sql4Cds.SSMS.Setup.msi /l*v SQL4CDSSetupLog.txt
```

If you run this and then hit the error in the installer, the details should be logged to the file SQL4CDSSetupLog.txt - please post this file so I can get the details of the error.

**Comment by EldonKlaassen** [comment]
Contents of log file:

=== Verbose logging started: 11/27/2022  8:10:17  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\WINDOWS\system32\msiexec.exe ===
MSI (c) (F0:34) [08:10:17:432]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (F0:34) [08:10:17:432]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (F0:DC) [08:10:17:464]: Resetting cached policy values
MSI (c) (F0:DC) [08:10:17:464]: Machine policy value 'Debug' is 0
MSI (c) (F0:DC) [08:10:17:464]: ******* RunEngine:
           ******* Product: MarkMpn.Sql4Cds.SSMS.Setup.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (F0:DC) [08:10:17:465]: Note: 1: 2203 2: MarkMpn.Sql4Cds.SSMS.Setup.msi 3: -2147287038 
MSI (c) (F0:DC) [08:10:17:465]: MainEngineThread is returning 2
=== Verbose logging stopped: 11/27/2022  8:10:17 ===

**Comment by MarkMpn** [comment]
What version(s) of SSMS do you have installed?

**Comment by EldonKlaassen** [comment]
SSMS v 18.12.1

Components Versions (from SSMS Help>About)

SQL Server Management Studio						15.0.18424.0
SQL Server Management Objects (SMO)						16.100.47021.0+7eef34a564af48c5b0cf0d617a65fd77f06c3eb1
Microsoft Analysis Services Client Tools						15.0.19750.0
Microsoft Data Access Components (MDAC)						10.0.22000.1219
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.22000

**Comment by MarkMpn** [comment]
When you ran that command line to generate the log file, were you running it from the directory that contains the .msi file you downloaded? Can you please try either navigating to the download directory first before running that command line, and/or specifying the full path to the .msi file rather than just the filename, e.g.

```
msiexec /i C:\Users\<your-username>\Downloads\MarkMpn.Sql4Cds.SSMS.Setup.msi /l*v SQL4CDSSetupLog.txt
```
