### ISSUE TITLE
WHERE clause doesn't support BETWEEN for numerical or date values

### ISSUE THREAD

**Issue by marcscheuner** [MarkMpn/Sql4Cds#27]
I tried to run a query like this in SQL-4-CDS (v2.3) :

```
select (list of columns)
from logtable
where logdate between '2020-09-25T00:00:00' and '2020-09-25T23:59:59'
```

but unfortunately, all I get is an error message:

> Unhandled WHERE clause: logdate between '2020-09-25T00:00:00' and '2020-09-25T23:59:59'

I had to rewrite the query to 

```
select (list of columns)
from logtable
where logdate >= '2020-09-25T00:00:00' and logdate  <= '2020-09-25T23:59:59'
```

While this is not a super critical bug - it would still be nice if SQL-4-CDS would support the "BETWEEN" SQL keyword

**Comment by MarkMpn** [comment]
Yes, this should be relatively simple - look out for this in the next update.

**Comment by marcscheuner** [comment]
Wonderful - looking forward to giving it a spin soonish ! 👍
