### ISSUE TITLE
Azure Data Studio: Not able to connect to Environment (AD /w MFA)

### ISSUE THREAD

**Issue by miseeger** [MarkMpn/Sql4Cds#278]
I successfully installed the vsix for Azure Data Studio and tried to connect to one of my DEV environments, using Azure AD but this failed:

> A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

![image](https://user-images.githubusercontent.com/1128963/215996498-54ca378a-23aa-4aa6-9252-dfc24fdf2843.png)

As you can see there is also the field for the "Tenant" missing if you compare the screenshot to yours from your blog article.

The instance name is correct and I successfully connected from SQL4CDS with XRMToolbox to this environment.

My fear is that the connection cannot be established because we have globally enabled MFA-Support for AD.

**Comment by MarkMpn** [comment]
It's working on my account with MFA so I'm pretty sure it's not related to that. Can I check what version of Azure Data Studio you're running?

**Comment by miseeger** [comment]
Thank you for the quick reply. Here is the info copied from the about dialog:

> Version: 1.41.1 (system setup)
> Commit: 33dce95b152227c4f10f6251ab30690fe9895c0c
> Date: 2023-01-28T00:46:39.274Z
> VS Code: 1.67.0
> Electron: 19.1.8
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Windows_NT x64 10.0.22000

**Comment by MarkMpn** [comment]
It looks like it's trying to use the TDS endpoint to run a query but it's failing to connect to it. It should only do that if it's detected that the TDS endpoint is enabled. Do you have that enabled? If it is enabled, are you able to connect to it using SSMS from this same computer?

**Comment by miseeger** [comment]
Yes TDS is enabled on all my environments. And I'm also able to connect to all my environments using SSMS (Server type: "Database Engine") from the same machine.

**Comment by MarkMpn** [comment]
Very strange - the error message indicates a network timeout error connecting to the TDS endpoint rather than any sort of authentication problem, as if the access was blocked by a firewall or something.

If you continue to get the error you can stop SQL 4 CDS using the TDS Endpoint in Azure Data Studio by going to File > Preferences > Settings, then expand Extensions > SQL 4 CDS configuration. There you can uncheck the "Use Tds Endpoint" option.

**Comment by miseeger** [comment]
Thank you for your efforts and the hint to disable TDS endpoint. Firewall is also a thing to consider. It's always the last thing you think about but mostly the reason why things won't work.
