### ISSUE TITLE
Autocomplete of Option Set values does not work

### ISSUE THREAD

**Issue by n0rthface** [MarkMpn/Sql4Cds#279]
Just tested the new release in XRMToolBox and saw that Autocomplete of Option Set values was announced as a new feature. I tested it with the exact SQL query from your screenshot in the blog and some other Option Sets in both standard and custom tables but I could not make it work. Already uinstalled and installed SQL4CDS and removed all local files. Am I missing anything to make this work? Otherwise great improvements and integration with Azure Data Studio is a great new feature!

**Comment by MarkMpn** [comment]
Can you try pressing Ctrl+Space to force the autocomplete list to appear?
