### ISSUE TITLE
No support for casting a DATETIME column to DATE only

### ISSUE THREAD

**Issue by marcscheuner** [MarkMpn/Sql4Cds#28]
I was trying to get the log entries for a particular date from SQL-4-CDS and tried like this:

```
select (list of columns)
from logtable
where cast(logdate as date) = '20200925'
```

which would work just fine in SQL Server (Mgmt Studio) - but in SQL-4-CDS, I only get an error message:

> Unsupported expression: cast(ambcust_logdate as date)

Any hope that this expression "cast(... as date)" will be supported in an upcoming version of SQL-4-CDS ?

**Comment by MarkMpn** [comment]
It's possible, but to do a thorough job would mean handling all the different rules from https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql, which is no small task. If there's other use cases that make this more important I'll take a deeper look at it, but as your example could be handled by `where logdate >= '2020-09-25' and logdate < '2020-09-26'` this seems a disproportionate amount of work for the benefit gained here.

**Comment by marcscheuner** [comment]
OK, thanks for the heads up - feel free to close this then

**Comment by MarkMpn** [comment]
I'll keep it open as I do see errors related to people trying to use this occasionally, just don't expect it to be implemented soon!

**Comment by rafek1241** [comment]
I have another use case for cast function:
```
update X
set 
property1 = y.Property2
from tableA X
join tableB y on x.prop = y.prop
```
Property1 with property2 are same values but with different type.

**Comment by MarkMpn** [comment]
This will be supported in v5 (soon)
