### ISSUE TITLE
Setting Batch Size in Query

### ISSUE THREAD

**Issue by SiPurdy** [MarkMpn/Sql4Cds#282]
Looking through code but there doesn't seem to be a way to disable ExecuteMultiple in updates for a specific query.

Use case we have is trying to update the entities enabled for Activity Feeds, issuing a command such as:
``` sql
update msdyn_postconfig set
    statecode=0
    , statuscode=1
where
    statecode=1 and
    msdyn_entityname in ('contact','account')
```
Updates are performed using an ExecuteMultiple, guessing based on the batchsize configured in parameters, results in the following error:
`You cannot start a transaction with a different isolation level than is already set on the current transaction`

It would be nice if this could be overrides the same wasy as MAXDOP
``` sql
update msdyn_postconfig set
    statecode=0
    , statuscode=1
where
    statecode=1 and
    msdyn_entityname in ('contact','account')
OPTION (MAXDOP 1, BATCHSIZE 1)   
```
Or have I just missed something? (This is with version 7.1).

Thanks

**Comment by MarkMpn** [comment]
Thanks for the clear write-up! You're correct that this can only be controlled in the global options at the moment rather than per-query, but if you do change the global batch size option to 1 then it will update the records individually rather than as part of an ExecuteMultipleRequest. I can look at adding a query hint to customize this in a future release though.

**Comment by SiPurdy** [comment]
Thanks @MarkMpn, consequence of being a hardened Dynamics developer dealing with the fuzziest of fuzzy requirements.

Was thinking further last night, probably the way it would have to work is take the minimum of the global option and query hint and use that batch size for the query; works to prevent situations where the query hints at a larger batch size than the user has selected in the global option.
