### ISSUE TITLE
Azure Data Studio extension doesn't load on Mac

### ISSUE THREAD

**Issue by MarkMpn** [MarkMpn/Sql4Cds#285]
```
[Error – 8:46:41 AM] Starting client failed
Launching server using command /Users/xxxxxxx/.azuredatastudio-insiders/extensions/mark carrington.azuredatastudio-sql4cds-7.1.0/out/sql4cdstoolsservice/MarkMpn.Sql4Cds.LanguageServer.exe failed.
```

https://markcarrington.dev/2023/01/31/sql-4-cds-v7-1-released/#comment-5807

**Comment by piyushpaliwal** [comment]
Hi @MarkMpn, just stumbled upon this issue and have been watching this since a week ago. I can help you test this feature when you make the updates. Let me know.

**Comment by MarkMpn** [comment]
Can you please try installing this version? Note you'll need to have then [.NET 7 runtime](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) installed already.

[azuredatastudio-sql4cds-7.1.1.vsix.zip](https://github.com/MarkMpn/Sql4Cds/files/11242776/azuredatastudio-sql4cds-7.1.1.vsix.zip)

Please let me know if this works for you or if you continue to have any errors - I'm hoping to get version 7.2 released shortly including this fix.

**Comment by piyushpaliwal** [comment]
yes, it works as expected! Thanks for the work on it

**Comment by MarkMpn** [comment]
Thanks for letting me know, I should have the next update released shortly.
