### ISSUE TITLE
Deprication of OData V2 on 30th of April 2023 - Any Impact on SQL4CDS?

### ISSUE THREAD

**Issue by miseeger** [MarkMpn/Sql4Cds#286]
Does the deprication/removal of OData V2 on 30th of April 2023 (https://powerapps.microsoft.com/de-at/blog/odata-v2-0-service-removal-date-announcement) have any impact on SQL4CDS?

Sorry for that maybe stupid question but I could not find any information about this and was not digging into the code that deep.

**Comment by MarkMpn** [comment]
No, SQL 4 CDS uses the standard SDK which does not use the OData 2 endpoint so it will be unaffected by this change.

**Comment by miseeger** [comment]
Thank you for this good news. 🙏🏼
