### ISSUE TITLE
[Suggestion] Add support for "name" display fields of lookup fields / option set fields

### ISSUE THREAD

**Issue by malam-dev** [MarkMpn/Sql4Cds#29]
I liked to turn on the SQL TDS option for queries because it made it easier to get display values for lookup and option set fields in a query like this:

    select 
    fullname
    ,parentcustomeridname
    ,new_someoptionsetfieldname
    from contact
    where new_someoptionsetfieldname in ('Item 1', 'Item 2')

instead of having to do joins for the lookups and hardcoding the option set values.

Since the SQL TDS endpoints are now disabled for everyone, if the behavior could be the same here it would be helpful. Right now you are able to select the name fields in the query without getting an error, but the results are just blank for those fields.

**Comment by MarkMpn** [comment]
Thanks for the suggestion. I'm looking into how I can improve the results for these virtual ___name fields for the next release.

**Comment by MarkMpn** [comment]
This is available now in 3.0.0, please let me know if you hit any problems with it!
