### ISSUE TITLE
Issue with Batch Execution with 7.2.1.0

### ISSUE THREAD

**Issue by SiPurdy** [MarkMpn/Sql4Cds#291]
Just updated to latest version (7.2.1.0).

Trying to run a simple update statement, have confirmation of the intent to update 16,720 records. On ok in the status I get a message "Updating {table} 8,260-12,455 of 16,720" before the error below:

```
One or more errors occurred.
ExecuteMultiple Request batch size exceeds the maximum batch size allowed!
System.NotSupportedException: ExecuteMultiple Request batch size exceeds the maximum batch size allowed!: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #5E97E9F7
```

My settings are for Insert/Update/Delete of batches of 10 records and use up to 4 worker threads. To me it looks like the batches are ignored and ALL of the records are batched into groups based on the worker threads and run in 1 go.

**Comment by MarkMpn** [comment]
Thanks for letting me know! I've managed to reproduce this here so hopefully I'll have a fix shortly. In the meantime please reinstall the previous version.
