### ISSUE TITLE
Query to Audit table does not return the correct value for column objectidtype when column is explicitly queried

### ISSUE THREAD

**Issue by n0rthface** [MarkMpn/Sql4Cds#296]
I just came across an issue with queries to "Audit" table.

Value of column "objectidtype" is returned correctly if I query for all columns:
![image](https://github.com/MarkMpn/Sql4Cds/assets/14167302/6e157368-9639-4563-b45b-8da6208e68c4)

Value of column "objectidtype" is returned with value "audit" in case I explicitly query for the column:
![image](https://github.com/MarkMpn/Sql4Cds/assets/14167302/39d3ca47-ee38-4df1-aaa6-377d54199f6a)

This happens to any objecttype and in any query combination (e.g. group by, join...). When I use an alias for the column, the value is returned as NULL.
![image](https://github.com/MarkMpn/Sql4Cds/assets/14167302/39a2e97a-6408-4b04-bad5-18dd324b07fc)

**Comment by MarkMpn** [comment]
Thanks for these details! It looks like Dataverse is doing something a bit different when it processes the queries for the `audit` entity compared to other tables. I'll look into adding some workarounds for this in the next update.
