### ISSUE TITLE
error translating sql query

### ISSUE THREAD

**Issue by fvinciguerra** [MarkMpn/Sql4Cds#30]
i tried to execute this sql update statament but i recivied error message:

"object reference not set to an insance of an object"

probaly is not possible translate this sql commnad in fetch xml query ?

UPDATE res_comune
SET    res_regioneid = r.res_regioneid
FROM   res_comune AS c
       INNER JOIN
       res_regione AS r
       ON c.res_regione = r.res_name;

**Comment by MarkMpn** [comment]
This seems to be due to you using the full `res_comune` entity name in the `UPDATE` clause, but aliasing it as `c` in the `FROM` clause. If you change your query to:

```sql
UPDATE c
SET res_regioneid = r.res_regioneid
FROM res_comune AS c
INNER JOIN
res_regione AS r
ON c.res_regione = r.res_name;
```

this should work as expected.

I'll look into improving the error message for the next release though.

**Comment by fvinciguerra** [comment]
Thank you so much
I tried your code and it runned correctly, anyway i tried to run mine on an instance of sql server and worked fine too.
Thanks again for the answer and most of all for your work with the plugin
Francesco

Da: Mark Carrington <notifications@github.com>
Inviato: mercoledì 28 ottobre 2020 15:21
A: MarkMpn/Sql4Cds <Sql4Cds@noreply.github.com>
Cc: Francesco Vinciguerra <f.vinciguerra@rsmanagement.it>; Author <author@noreply.github.com>
Oggetto: Re: [MarkMpn/Sql4Cds] error translating sql query (#30)


This seems to be due to you using the full res_comune entity name in the UPDATE clause, but aliasing it as c in the FROM clause. If you change your query to:

UPDATE c

SET res_regioneid = r.res_regioneid

FROM res_comune AS c

INNER JOIN

res_regione AS r

ON c.res_regione = r.res_name;

this should work as expected.

I'll look into improving the error message for the next release though.

**Comment by MarkMpn** [comment]
Good catch, I've handled this now in d89b458e66bbbf4fb1259ce2f8203158f80e3d49
