### ISSUE TITLE
"Order by is not supported with group by" with no ORDER BY

### ISSUE THREAD

**Issue by fowl2** [MarkMpn/Sql4Cds#300]
SQL 4 CDS 7.1.0.0 in XRM Toolbox 1.2023.2.64

Query:
``` SQL
SELECT action, COUNT(*) FROM audit GROUP BY action
```

Error:
```
Order by is not supported with group by.
See the Execution Plan tab for details of where this error occurred
```

Note there is no order by in the query.

Execution Plan:

![image](https://github.com/MarkMpn/Sql4Cds/assets/12844147/a9770d26-388c-4ec2-93c6-d4a427a73760)

And the generated/failing FetchXML:
``` xml
<fetch xmlns:generator='MarkMpn.SQL4CDS' aggregate='true'>
  <entity name='audit'>
    <attribute name='action' alias='action' groupby='true' />
    <attribute name='auditid' alias='count' aggregate='count' />
    <order alias='action' />
  </entity>
</fetch>
```

If I modify the FetchXML to remove the `<order>`:
``` xml
 <fetch xmlns:generator="MarkMpn.SQL4CDS" aggregate="true">
  <entity name="audit">
    <attribute name="action" alias="action" groupby="true" />
    <attribute name="auditid" alias="count" aggregate="count" />
  </entity>
</fetch>
```

The query succeeds. 

Thanks for your work on this amazing tool!

**Comment by MarkMpn** [comment]
Thanks for the details - this is part of the `audit`-specific work I've been looking at as part of #296, it'll be fixed as part of the next update.
