### ISSUE TITLE
Lazy Loading of Metadata

### ISSUE THREAD

**Issue by SiPurdy** [MarkMpn/Sql4Cds#301]
We have a few situations where it's advantageous to write defensive sql scripts whose main processing only happens when required, for example the below where it checks the entity exists before processing.

```sql
if exists(
    select metadataid
    from metadata.entity
    where logicalname='mbs_pluginprofile') begin
 
    delete from mbs_pluginprofile
    where createdon < GETUTCDATE() - 30
end
```

When run from XrmToolbox it fails with the error "Unknown table mbs_pluginprofile: mbs_pluginprofile".

Our main intention is to run scripts like this through MarkMpn.Sql4Cds.Engine where I've noticed the first time a command runs within a connection, all(?) entity metadata is retrieved before processing starts.

Desired result would be that any metadata is only retrieved when required allowing for full skipping of blocks based on conditions.

**Comment by MarkMpn** [comment]
Interesting suggestion - I can see the benefit of this and it's something I'll try to look at in a future update, but this would involve quite a major change so it won't be in the next version I'm working on now.
