### ISSUE TITLE
Escaping of not so special characters required?

### ISSUE THREAD

**Issue by jessaskey** [MarkMpn/Sql4Cds#303]
I attempted to run an insert statement like this example below and received an error due to the question mark in the first value. I tried putting a backslash in front of it.. and it worked but then my value actually had a backslash in D365 as well?  So `'Erik\?' `literally inserted `'Erik\?' `and not `'Erik?'`

`insert into contact(firstname,lastname,telephone1,mobilephone,emailaddress1,jobtitle,description,ownerid,owneridtype,nbb_salesparentaccount,nbbmkt_contacttype,donotfax) values('Erik?','','','','','Manager','','C9F41FC9-9254-ED11-BBA3-0022482A998F','systemuser','DF012380-49B9-ED11-83FD-000D3A5C6AB1',769680000,1)`

Also, this one threw an error too... not sure how to fix this one..

`insert into contact(firstname,lastname,telephone1,mobilephone,emailaddress1,jobtitle,description,ownerid,owneridtype,nbb_salesparentaccount,nbbmkt_contacttype,donotfax) values('Scott','','','','','Buyer / GM\?','','059327C3-9254-ED11-BBA3-0022482A998F','systemuser','3520D58C-53B9-ED11-83FD-000D3A5C6AB1',769680000,1)`

8:32:40 AMStarted executing query at Line 1
Incorrect syntax near \.
Total execution time: 00:00:00

**Comment by MarkMpn** [comment]
I can't reproduce any errors with these, both queries work fine on my test instances. Can you share the details of the errors you received please?

**Comment by jessaskey** [comment]
Wow... yeah, that is strange because that first statement was giving me that error shown at the end of post but with 'Incorrect Syntax near ?'... it gave me the error last night and early this morning... but now when I ran it against our dataverse environment just now, it worked fine... So im at a loss. Im running a set of statements now (42K of them to be exact) so I will see if it gets through them all... it appears that since each of my insert statements is on a seperate line, that SQL4CDS is running them one at a time but maybe there is a buffer size limit that is somehow truncating the string arbitrarily around that ? mark and so there is a phantom error. My total set of insert statements are 42,513 command lines consisting of 13,642,102 characters. 

Sensibly, I should batch those in groups of 10K probably, but I have done this in the past effectively.

This will take a few hours if it does complete, so let me report back.  Thank you!

![image](https://github.com/MarkMpn/Sql4Cds/assets/3683098/dfe67fd8-9813-4542-8efc-771bc56fdfe1)

**Comment by jessaskey** [comment]
Okay, it took 20 minutes (probably to parse my monstrosity), but it failed on line 162 again complaining about the question mark. I will break my queries down into more sensible chunks and report back.

![image](https://github.com/MarkMpn/Sql4Cds/assets/3683098/5c40afbd-5a3f-429c-b4b0-893ada254c8f)

**Comment by jessaskey** [comment]
So weird... just won't get past this question mark.... any other suggestions?

![image](https://github.com/MarkMpn/Sql4Cds/assets/3683098/e986bf7c-845b-45d0-841e-7a6fa00e9220)

**Comment by MarkMpn** [comment]
It does look from the syntax highlighting that there's a mismatched quote somewhere higher up your script which would be worth checking for.

You might also want to try inserting multiple values in a single statement such as

```
INSERT INTO contact (firstname, lastname)
VALUES ('a', 'b'), ('c', 'd'), ('e', 'f')
```

Not sure if it'll help with this specific error but you should find this runs through significantly faster as it can take advantage of batching and multi-threading of the create requests.

**Comment by jessaskey** [comment]
You are spot on.... I had an errant 'lastname' value that had a single quote in it and I was not escaping it properly, so the parser was happily interpreting the rest of the SQL as text and it finally barfed in a random location (the question mark in this case).

So.. 100% user error on this end. Thank you for helping, I will attempt to keep these errors off your issue board. :-)  

Jess
