### ISSUE TITLE
Suggestion ContinueOnError on DML Requests

### ISSUE THREAD

**Issue by SiPurdy** [MarkMpn/Sql4Cds#304]
There are a few situations where being able to run a DML statement which continues on error rather than aborting on the first error would be useful. Not something for every request, so ideally something definable as a hint, eg

```sql
update contact set
firstname='Steve'
where statecode=0
OPTION (USE HINT('CONTINUE_ON_ERROR'))
```
I've had a number of instances where mass record deletion (not using bulk deletion jobs) have failed due to other processes deleting records before Sql4Cds gets round to it.

It would be a bonus if in the case of deletes, if a record fails because its not present, that failure could be ignored.

**Comment by MarkMpn** [comment]
Thanks for the suggestion. I understand the case where an `UPDATE` or `DELETE` fails because the record no longer exists, and this should probably be default behaviour. I'm not sure about ignoring more general errors though - what's you use-case for this?

**Comment by SiPurdy** [comment]
It's more to do with if you're running an update on 100k records, and 50 individual records spread evenly through the set fail. If there was a CONTINUE_ON_ERROR option, it's nicer to have it fail at the end (with all 50 exceptions) rather than have to re-run the query 50 times.

I've had it with plugins/real time workflows with deadlocking; it's nicer after the first run through be able to knock off the remaining 50 records, rather than re-run with 98k records, then 96k records...

**Comment by MarkMpn** [comment]
OK, so you would still want the update to fail with the same error message, but only after it's updated as many records in the batch as possible?

**Comment by SiPurdy** [comment]
Yes if by batch we mean the whole set of 100k records, rather than the 10 we're executing in the sub-batch.
