### ISSUE TITLE
Azure Data Studio - No Results 

### ISSUE THREAD

**Issue by chaffee007** [MarkMpn/Sql4Cds#307]
I am using the SQL 4 CDS extension in Azure Data Studio, but I am not getting a results set when running queries.  
![image](https://github.com/MarkMpn/Sql4Cds/assets/16105932/bd021872-2124-4f0f-a8ab-3772a811d7a3)

**Comment by MarkMpn** [comment]
I think this will be the same issue as #298, can you try changing the setting described in that issue please?
