### ISSUE TITLE
Incorrect Aggregates using Count(*)

### ISSUE THREAD

**Issue by rhanoudi** [MarkMpn/Sql4Cds#308]
I love the SQL4CDS utility and I use it all the time. I noticed using the latest version (7.2.2.0) that I'm getting incorrect aggregate result when using count(*):

Select COUNT(*)
From contact
Where statecode = 0 

![image](https://github.com/MarkMpn/Sql4Cds/assets/16481263/e9eaad41-dd1c-4897-a265-faa57c343edc)

My current work around is select a field value
Select contactid
From contact
Where statecode = 0 

![image](https://github.com/MarkMpn/Sql4Cds/assets/16481263/61f806f6-61ff-4aac-bd62-710b3240dcbb)

**Comment by MarkMpn** [comment]
I'm struggling to reproduce this problem. Could you enable the "Display Actual Execution Plan" option (next to "Format" in the toolbar) and run the aggregate query again, then go to the "Execution Plan" tab next to the Results tab and take a screenshot of that please?

**Comment by rhanoudi** [comment]
Hi Mark, 

Thank you for looking into this issue. See attached.

![image](https://github.com/MarkMpn/Sql4Cds/assets/16481263/5dac12df-70f3-43d3-9f86-b2f3c420992c)

**Comment by rhanoudi** [comment]
Hello again, I realized after I posted my message that I posted the estimate query plan, not the actual. Here is the actual query plan:

![image](https://github.com/MarkMpn/Sql4Cds/assets/16481263/d64ef1a2-edf1-4b8c-80a3-ed5c96de91e1)

**Comment by MarkMpn** [comment]
I think I've identified a bug with this partitioned aggregate operator when using multi-threading the latest release. Can you please try changing the maximum number of threads in your settings to 1?

**Comment by rhanoudi** [comment]
Hi Mark,

Yes, I get the right results now when I set the threads to 1. Amazing work. Thank you!

Rayan
