### ISSUE TITLE
Error in grid by select results (2 text columns,  103.240 records) for copy

### ISSUE THREAD

**Issue by AntonUdalow** [MarkMpn/Sql4Cds#31]
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei MarkMpn.Sql4Cds.SqlQueryControl.Grid_RecordClick(Object sender, CRMRecordEventArgs e)
   bei xrmtb.XrmToolBox.Controls.CRMGridView.OnRecordEvent(CRMRecordEventArgs e, CRMRecordEventHandler RecordEventHandler)
   bei System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   bei System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MarkMpn** [comment]
Thanks for reporting this. Is the a particular point on the grid you have to click on to get this error?

**Comment by AntonUdalow** [comment]
I click in the left top corner to select all records.

**Comment by MarkMpn** [comment]
Thanks for this, this will be fixed in the next release. In the meantime you can click on any cell within the grid and press <kbd>Ctrl</kbd>+<kbd>A</kbd> to select all the cells
