### ISSUE TITLE
v7.3.0 Azure Data Studio extension shows an error

### ISSUE THREAD

**Issue by MikhailProfile** [MarkMpn/Sql4Cds#312]
Good day, 

Trying to start using ADS extension, I can connect to Dataverse but when trying to generate a script to query a data I have the error:
**[Error - 20:03:30] Request scripting/script failed.
  Message: Method with name "scripting/script" not found.
  Code: -32601**

![image](https://github.com/MarkMpn/Sql4Cds/assets/2986524/a46ad8c8-cac3-4663-b7f4-8968483648a7)

But all works well when I create script manually. 

Thanks!

**Comment by MarkMpn** [comment]
Yes, I haven’t implemented that option yet, or the others in that menu. I should be able to do this one in a future update though.

**Comment by MikhailProfile** [comment]
Ok, great! Thanks Mark! 

Should I close the issue? Or just leave it?

**Comment by MarkMpn** [comment]
Leave it open so I remember to implement it!
