### ISSUE TITLE
FakeXrmEasy and Sql4Cds nuget package

### ISSUE THREAD

**Issue by sybaris** [MarkMpn/Sql4Cds#318]
Hi,

I would like to know if it's possible to use Sql4Cds engine in my program, and make unit tests using FakeXrmEasy, to test my Sql queries ?

My first attempt throw an exception : 
_FakeXrmEasy.Abstractions.Exceptions.OpenSourceUnsupportedException: 'Exception occurred: The organization request type 'Microsoft.Xrm.Sdk.Messages.RetrieveEntityRequest' is not yet supported... . If you are using FakeXrmEasy in an Open Source project please raise an issue via our GitHub issue tracker at https://github.com/DynamicsValue/fake-xrm-easy. Also please do consider giving back to the OSS community by contributing back to our project via a pull request. The community will appreciate any kind contribution even if small: typos, comments, steps to reproduce a bug, documentation, or new ideas for new features. If you are unsure about our licensing, please have a look at our licensing FAQ here: https://dynamicsvalue.github.io/fake-xrm-easy-docs/licensing/faq/'_

Regards
Sybaris

**Comment by MarkMpn** [comment]
Yes, SQL 4 CDS works with FakeXrmEasy and it's used extensively in the test in the MarkMpn.Sql4Cds.Engine.Tests project. If you're encountering any issues with FakeXrmEasy I'd suggest following the links in the exception message to raise an issue with that project directly.

**Comment by sybaris** [comment]
Hi
Thanks.
I raise this issue https://github.com/DynamicsValue/fake-xrm-easy/issues/106 in FakeXrmEasy repository.
Regards
Sybaris

**Comment by jordimontana82** [comment]
Hey @MarkMpn 

I hope you're doing well.

It seems this is triggered via a MessageCache object, however, I'm not sure what sdkmessagerequest is used for.  

https://github.com/MarkMpn/Sql4Cds/blob/5819139ad96dfa34007c3fcce6f87ac0100068d2/MarkMpn.Sql4Cds.Engine/MessageCache.cs#L60

I've certainly know we have entities like sdkmessage, sdkmessageprocessingstep, sdkmessagefilter, etc but I never seen a "sdkmessagerequest" entity.  I was curious to see if this was a new entity introduced but I couldn't find it on Advanced Find like the other sdkmessage* entities either.

Is this a new magic "hidden" entity or a custom one used internally in the library?

Thanks!
@sybaris

**Comment by MarkMpn** [comment]
It's a standard part of the data model, not something that's been introduced recently. It's part of a series of tables that's used to describe the request and response parameters for SDK messages, both OOB and custom. You can see other examples of its use in the Custom Action Tester / Custom API Tester tool at https://github.com/rappen/CustomActionTester/blob/5a3108b9add4f2d3b6f4e6f4b9c58bcf33cfdbd8/CAT/CATTool.cs#L84

If it's causing a problem you can pass in your own `IMessageCache` implementation, e.g. https://github.com/MarkMpn/Sql4Cds/blob/5819139ad96dfa34007c3fcce6f87ac0100068d2/MarkMpn.Sql4Cds.Engine.Tests/StubMessageCache.cs

**Comment by jordimontana82** [comment]
Thanks for the quick reply @MarkMpn 

Ah so the metadata for input and output params of good old custom actions... makes sense.

As I was mostly using the /generateActions and early bound I didn't have to retrieve it for all the unit tests I had so far, but good to know!

**Comment by jordimontana82** [comment]
I've also raised this issue in case they want to update the docs..... https://github.com/MicrosoftDocs/powerapps-docs/issues/4541

**Comment by sybaris** [comment]
Hi,

First, thanks @jordimontana82  and @MarkMpn for getting in touch and allowing me to move forward on my question...
Alas, I do not have your level of skills, and an explanation/example would be useful to me.

I understand that IMessageCache seems to be a solution, but an example could be usefull for me.

As reminder, the unit test I want to write is available here : https://github.com/DynamicsValue/fake-xrm-easy/issues/106

Thanks for your help
Regards
Sybaris

**Comment by sybaris** [comment]
Any news ?

**Comment by jordimontana82** [comment]
Hy @sybaris ,

I'm not an expert on the internals of Sql4Cds (@MarkMpn is your man), but here's an example in the base test class using a StubMessageCache. 

https://github.com/MarkMpn/Sql4Cds/blob/master/MarkMpn.Sql4Cds.Engine.Tests/FakeXrmEasyTestsBase.cs#L40

Out of curiosity, what are you trying to achieve? (i.e. are these SQL queries executed by a soon to be production code by any chance?)

Another alternative as opposed to using IMessageCache, would be to provide FakeXrmEasy with the necessary metadata entities that Sql4Cds needs.  Here's an example about adding custom metadata in the docs: https://dynamicsvalue.github.io/fake-xrm-easy-docs/quickstart/advanced/metadata/

You would need to do that for "sdkmessagerequest" and all the other entities it complains about.

Are you using late bound or early bound classes too?
