### ISSUE TITLE
query from query  error Unhandled SELECT FROM clause:

### ISSUE THREAD

**Issue by vhkt** [MarkMpn/Sql4Cds#32]
I like to build a query on top of another query:
select sum(a.column from ( select invoice.totalamount from invoice where invoice.year = yyyy and invoice.period = mm) as a

**Comment by MarkMpn** [comment]
You can't use a subquery like this in SQL 4 CDS, but you could probably get the result you want using

```sql
SELECT sum(totalamount)
FROM   invoice
WHERE  DATEPART(year, datedelivered) = 2020 AND
       DATEPART(month, datedelivered) = 11
```
