### ISSUE TITLE
Too many questions when trying to delete records.

### ISSUE THREAD

**Issue by holgerkpedersen** [MarkMpn/Sql4Cds#320]
I'm using XrmToolBox. SQL 4 CDS. When I want to delete something, I get 5 questions "Delete will affect <x> <tablename>... Do you want to proceed?" Yes/No. The number of times the question is asked is 5 when I've done 5 executions  in same session, and The number of times the question is asked is 50 when I've done 50 executions  in same session. Can you correct this bug?

**Comment by MarkMpn** [comment]
Can you let me know what version of SQL 4 CDS you're running please? This sounds like the same issue as #191 which was fixed last year.
