### ISSUE TITLE
after execute query when i select all output an exception window is thrown

### ISSUE THREAD

**Issue by vhkt** [MarkMpn/Sql4Cds#33]
when i select all output from execute query i get an exception popup window. when you press continue it is not an issue:

the details screen contains this and a long list of loaded assemblies
Zie het einde van dit bericht voor meer informatie over het aanroepen 
van JIT-foutopsporing (Just In Time) in plaats van dit dialoogvenster.

************** Tekst van uitzondering **************
System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij MarkMpn.Sql4Cds.SqlQueryControl.Grid_RecordClick(Object sender, CRMRecordEventArgs e)
   bij xrmtb.XrmToolBox.Controls.CRMGridView.OnRecordEvent(CRMRecordEventArgs e, CRMRecordEventHandler RecordEventHandler)
   bij System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   bij System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   bij System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bij System.Windows.Forms.Control.WndProc(Message& m)
   bij System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladen assembly's **************
************** JIT-foutopsporing **************
Als u JIT-foutopsporing wilt inschakelen, moet in het configuratiebestand voor deze
toepassing of computer (machine.config) de waarde
jitDebugging in het gedeelte system.windows.forms zijn ingesteld.
De toepassing moet ook zijn gecompileerd terwijl foutopsporing
was ingeschakeld.

Bijvoorbeeld:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wanneer JIT-foutopsporing is ingeschakeld, worden onverwerkte uitzonderingen
naar het JIT-foutopsporingsprogramma gestuurd dat op de computer is geregistreerd
en worden niet door dit dialoogvenster verwerkt.

**Comment by MarkMpn** [comment]
Closing as a duplicate of #31. A fix for this is ready for the next version
