### ISSUE TITLE
New Version 7.4.0 Update Issue

### ISSUE THREAD

**Issue by sulimanbenhalim** [MarkMpn/Sql4Cds#334]
I am getting this error:

Method not found: 'System.Nullable`1<Boolean> Microsoft.Xrm.Sdk.Metadata.EntityMetadata.get_IsRetentionEnabled()'.

when executing any query or opening the Entities folder

**Comment by MarkMpn** [comment]
Can you confirm the version of XrmToolBox you're using please?

**Comment by sulimanbenhalim** [comment]
7.4.0

**Comment by MarkMpn** [comment]
That's the SQL 4 CDS version. Can you check the version of XrmToolBox itself (shown in the top title bar of the window or in the bottom right of the Help > About XrmToolBox screen)?

**Comment by MitchellZhang** [comment]
After updating XrmToolBox to the latest version, this error disappears.
