### ISSUE TITLE
Unable to load newest version

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/Sql4Cds#336]
After installing 7.4.0 it caused this issue:  https://github.com/MscrmTools/XrmToolBox/issues/1274

After deleting the dll that was causing the XTB to not load, I can't open the tool.

**Comment by MarkMpn** [comment]
In the linked issue you mentioned that you resolved the error by deleting the failing tool, what is the current state of this? Is XTB loading but SQL 4 CDS is not? If so, do you get any error when trying to load SQL 4 CDS?

**Comment by daryllabar** [comment]
Yes, I can't load SQL4CDS now, but I'm sure it's not too helpful:

![image](https://github.com/MarkMpn/Sql4Cds/assets/9728423/d0a36101-aeea-42eb-82bd-45ba71797bec)

**Comment by MarkMpn** [comment]
You’re right, that’s not too helpful. Any chance you could run it with a debugger attached to see what the inner exception is?

**Comment by daryllabar** [comment]
That would require downloading the project code base correct?

**Comment by MarkMpn** [comment]
No, just attach the debugger to XrmToolBox.exe and disable the “just my code” option in the debugger settings. Try to launch SQL 4 CDS and the debugger should break once the exception is thrown. You won’t get the full source of where the exception is coming from but you should get the details of the original exception and its call stack to give me some clues.

**Comment by daryllabar** [comment]
The type initializer for 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' threw an exception.
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration..ctor(String instrumentationKey)
   at MarkMpn.Sql4Cds.XTB.PluginControl..ctor(Object plugin)
- Inner Exception: Method not found: 'Boolean System.Diagnostics.Activity.get_ForceDefaultIdFormat()'.
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.<>c.<.cctor>b__13_0()
   at Microsoft.ApplicationInsights.ActivityExtensions.TryRun(Action action)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration..cctor()

![image](https://github.com/MarkMpn/Sql4Cds/assets/9728423/5939e9de-4644-49e6-aaec-4ad56def97c4)

**Comment by MarkMpn** [comment]
Thanks! Looks like a mismatched assembly version. As a starting point, could you let me know what version of XTB you’re running and attach a zip file of your entire Plugins folder so I can compare with mine?

I’m away for a week now but I’ll check when I get back.

**Comment by daryllabar** [comment]
Emailed you a link to the plugins zip folder
Running XTB 1.2023.6.65

**Comment by MarkMpn** [comment]
Thanks Daryl. It looks like this is triggered by the System.Diagnostics.DiagnosticSource.dll file in the Plugins folder. I'm not sure what has introduced this file but if I delete it then I can open v7.4 as expected. Can you check if this works for you?

**Comment by daryllabar** [comment]
I'm working now
