### ISSUE TITLE
Poor performance (teammembership / systemrole) after update  to 7.4.0

### ISSUE THREAD

**Issue by GerritRega** [MarkMpn/Sql4Cds#338]
Hi,

i'm really new by using SQL4CDS and SQL coding.

I'm using SQL4CDS to check if Teams or Security roles are available and add it if not.

```sql
if not exists (select * from teammembership where teamid = (select teamid from team where name = 'TEAMNAME') and systemuserid = @USERGUID)
  insert into teammembership (teamid, systemuserid)
  values ((select teamid from team where name = 'TEAMNAME' ),@USERGUID); 
```

or

```sql
if not exists (select * from systemuserroles where roleid = (select roleid from role where name = 'ROLENAME' and businessunitid = @BUID) and systemuserid = @USERGUID)
  insert into systemuserroles (roleid, systemuserid)
  values ((select roleid from role where name = 'ROLENAME' and businessunitid = @BUID),@USERGUID);
```

This Line was quick in the past now they take 20-30 Seconds for one Team / Role
<img width="480" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/59688016-7d1e-4bd1-a6e7-34724cac4616">

If i change to the id instead of * it make no difference.

If we change it to join it's quick

```sql
if not exists ((select teammembershipid from teammembership tm join Team T on t.teamid = tm.teamid where t.name = TEAMNAME' and tm.systemuserid = @USERGUID))
  insert into teammembership (teamid, systemuserid)
  values ((select teamid from team where name = 'TEAMNAME' ),@USERGUID);

if not exists (select systemuserroleid from systemuserroles  sur join role r on r.roleid = sur.roleid where r.name = 'ROLENAME' and r.businessunitid = @BUID and sur.systemuserid = @USERGUID)
  insert into systemuserroles (roleid, systemuserid)
  values ((select roleid from role where name = 'ROLENAME' and businessunitid = @BUID),@USERGUID);
```

I'm not sure if this is a wanted behavior after the update or not.
Any ideas from your side?

Otherwise i need to update a lot of scripts :-)

Thanks and best regards

**Comment by GerritRega** [comment]
Hi  @MarkMpn, thanks for your quick reply. If you need more, do not hesitate to contact me

**Comment by MarkMpn** [comment]
I've just had a look at these queries and the query plan I get hasn't changed in the latest update. Do you know what version you were on previously when these ran faster? Can you also please:

1. Enable the "Display Actual Execution Plan" option in the toolbar before running the query
2. Run the query
3. Once the query is complete, switch to the Execution Plan tab and take a screenshot - if you need to scroll to get the whole execution plan please do so and take a screenshot of each section

Please repeat this for both the earlier version where you were getting better performance and the latest version.

Can you also please let me know if it is correct that this user has over 185,000 roles? In my tests it should only retrieve at most all the roles that are currently assigned to the user.

**Comment by GerritRega** [comment]
hi Marke, the earlier version was i think 7.3.0.0 to use up to date versions-
We have a lot of roles, different BU and this count up the roles.
We've the same on Team base. Here we have a lot of less teams in count.

I'll give you th eneeded informations as soon as possible.

**Comment by GerritRega** [comment]
7.3.0 old script  
![image](https://github.com/MarkMpn/Sql4Cds/assets/61063673/c57e25d8-2865-4d97-8f5a-c58b87f49e2d)
7.4.0 old script
![image](https://github.com/MarkMpn/Sql4Cds/assets/61063673/01401224-d232-4349-a962-bbc26bf80733)
7.4.0 updated script
![image](https://github.com/MarkMpn/Sql4Cds/assets/61063673/94402464-2638-4872-a95a-9e3da43bd1e1)


7.3.0 Teammembership - original script: 
<img width="774" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/e68ae3bb-fb3f-4cdd-88a5-b4fd05ad13d5">

7.4.0 Teammembership - original script:
<img width="904" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/4a673214-486c-4648-8e55-cdb8b3656444">
<img width="429" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/ea7896b3-a969-4df5-a0da-f2bc258ef355">

7.4.0 Teammembership - updated script:
<img width="508" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/2a022c63-520d-478e-b6be-e742bcb65e7d">


7.3.0 systemuserrole - original script
<img width="771" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/8f0d80b9-a5a5-40a4-a554-ee9f6ef671ae">
<img width="427" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/5f743b16-8495-479b-875a-0a8b14f8617a">

7.4.0 systemuserrole - original script
<img width="874" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/bcb01754-3c0f-40e3-9a09-181d95012f7f">
<img width="425" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/1ecb364c-a39a-44cc-80c5-ec208760e681">

7.4.0 systemuserrole - updated script
<img width="431" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/6d09cbbd-2189-482d-9cf2-b88efef27c8b">
<img width="422" alt="image" src="https://github.com/MarkMpn/Sql4Cds/assets/61063673/f4f9d1ef-e05f-4c20-ae94-d9a80d8db700">


I hope this will help to display more.

**Comment by MarkMpn** [comment]
Thanks, that’s helpful. I think I’ve identified the cause, I should be able to revert it to at least the performance of previous versions in the next update but I’ve also got some ideas on how to improve this further as well.
