### ISSUE TITLE
statecode/statuscode update error "Unable to cast object of type"

### ISSUE THREAD

**Issue by chironh** [MarkMpn/Sql4Cds#339]
Having issues with a simple lead qualify update statement:

```
UPDATE lead
SET statecode = 1, statuscode = 3
WHERE leadid = 'cfe9286d-be77-4bcc-9071-ea56ef4e7448'

Unable to cast object of type 'Microsoft.Xrm.Sdk.Messages.ExecuteTransactionRequest' to type 'Microsoft.Xrm.Sdk.Messages.UpdateRequest'.
```

I've also tried different versions and version 6.4 works as expected. 
I'm not sure in which specific version this problem was introduced, but it has to be 7.x.

**Comment by MarkMpn** [comment]
Thanks for letting me know. I’ll get this fixed in the next update.

For the moment you should be able to work around this by setting the batch size to 1, either in the settings page or using the [`BATCH_SIZE`](https://github.com/MarkMpn/Sql4Cds/wiki/Query%20Hints#batch_size) query hint
