### ISSUE TITLE
【Request】OPENJSON() & JSON_QUERY()

### ISSUE THREAD

**Issue by hiroyuki0415** [MarkMpn/Sql4Cds#340]
Could you please add the following implementation ?

■ [OPENJSON](https://learn.microsoft.com/en-us/sql/relational-databases/json/convert-json-data-to-rows-and-columns-with-openjson-sql-server?view=sql-server-ver16)
  - I want to apply `CROSS APPLY` to the return value. like :
```sql
-- cloudflow : parameters = 1 : N
SELECT w.name,
       trigger_param.*
FROM   workflow AS w 
       CROSS APPLY OPENJSON(JSON_QUERY(w.clientdata, 'properties.definition.triggers.manual.inputs.schema.properties')) AS trigger_params
WHERE  w.category = 5;
```

<details>
  <summary>Click me</summary>

`JSON_QUERY(w.clientdata, 'properties.definition.triggers.manual.inputs.schema.properties')` is like: 

```json
{
    "text": {
        "title": "param1",
        "type": "string",
        "x-ms-dynamically-added": true,
        "description": "desc1",
        "x-ms-content-hint": "TEXT"
    },
    "text_2": {
        "title": "param2",
        "type": "string",
        "x-ms-dynamically-added": true,
        "description": "desc2",
        "x-ms-content-hint": "TEXT"
    },
    "number": {
        "title": "param3",
        "type": "number",
        "x-ms-dynamically-added": true,
        "description": "desc3",
        "x-ms-content-hint": "NUMBER"
    }
}
```
</details>

■ [JSON_QUERY](https://learn.microsoft.com/en-us/sql/t-sql/functions/json-query-transact-sql?view=sql-server-ver16)

- I know there is already a function `JSON_VALUE()`. I want a function that accepts **arrays** and **objects** as return values

Thanks in advance for your support.

P.S. 
I'm always indebted to this plugin of yours.

**Comment by MarkMpn** [comment]
This is covered by #383 and will be in the next release.
