### ISSUE TITLE
[Suggestion] Support for "Execute on Behalf Of"

### ISSUE THREAD

**Issue by marcscheuner** [MarkMpn/Sql4Cds#35]
When using the CRM SDK or the REST API, I have the ability (if I have the necessary permission) to do e.g. bulk update operations "on behalf of" someone else - e.g. I can update thousands of entities and have some service account used for the "ModifiedBy" value of those entities.

Is there any chance SQL-4-CDS could support this feature? Right now, it's the best and easiest way to do bulk updates - but it carries the drawback of my own name showing up as the "Modified By" user for all the entities I've updated.

**Comment by MarkMpn** [comment]
You can partially do this today using the standard XrmToolBox "Impersonate" button. This works for the main/initial connection, but does not work well for multiple connections. I'll investigate how this can be extended to cover more complex scenarios.

**Comment by MarkMpn** [comment]
This will now be included in the next release. Thanks for the suggestion!
