### ISSUE TITLE
Convert query to FetchXML creates 2 separate XMLs

### ISSUE THREAD

**Issue by tmykhaylovsky** [MarkMpn/Sql4Cds#355]
Hi @MarkMpn, thank you once more for this tool. Incredible.

**Query**

```sql
select e.name, e.logicalname
,o_e.ops_name, o_e.ops_logicalname
from entity e
inner join ops_entity o_e on o_e.ops_logicalname = 'account'
where e.name = 'Account' and e.logicalname = 'account'
```

**Output**

```xml
<fetch xmlns:generator='MarkMpn.SQL4CDS'>
  <entity name='entity'>
    <attribute name='name' />
    <attribute name='logicalname' />
    <filter>
      <condition attribute='name' operator='eq' value='Account' />
      <condition attribute='logicalname' operator='eq' value='account' />
    </filter>
  </entity>
</fetch>
```

```xml
<fetch xmlns:generator='MarkMpn.SQL4CDS'>
  <entity name='ops_entity'>
    <attribute name='ops_name' />
    <attribute name='ops_logicalname' />
  </entity>
</fetch>
```

**Expecting 1 FetchXML.**

Curious if entity table is a metadata table that is not possible to join with a custom ops_entity table I created.

**This SQL is properly converted with a link entity**

```sql
select *
from account a
join contact c on a.primarycontactid = c.contactid
```

**Comment by MarkMpn** [comment]
You can join to this table, but for it to be converted to a FetchXML link-entity the join must be on a simple equality of one column from each table. The join condition in your example is an equality between a column on your custom table and a literal value:

`o_e.ops_logicalname = 'account'`

If you rewrite your query as:

```sql
select e.name, e.logicalname
,o_e.ops_name, o_e.ops_logicalname
from entity e
inner join ops_entity o_e on o_e.ops_logicalname = e.logicalname
where e.name = 'Account' and e.logicalname = 'account'
```

you should get the result you're looking for.

**Comment by tmykhaylovsky** [comment]
Just realized I didn't write the query properly.

The left join condition was a constant comparison.

Thank you for offering the solution.

All the best!
