### ISSUE TITLE
【Bug】AND in ON condition of INNER JOIN is not working

### ISSUE THREAD

**Issue by hiroyuki0415** [MarkMpn/Sql4Cds#360]
```sql
SELECT e.logicalname,
       a.logicalname,
       a.targets
FROM   metadata.entity AS e
       INNER JOIN
       metadata.attribute AS a
       ON e.logicalname = a.entitylogicalname
          AND a.targets IS NOT NULL
WHERE  e.logicalname IN ('systemuser');

```

This SQL result also **includes** `NULL` "targets" values.
`AND a.targets IS NOT NULL` is not working.

Thanks in advance for your support.

**Comment by hiroyuki0415** [comment]
The bug is not fixed in ver7.6.1.0

**Comment by MarkMpn** [comment]
This is definitely working for me, can you please share the execution plan and results of this query, and the results of running `SELECT @@VERSION`?

**Comment by hiroyuki0415** [comment]
very sorry.
I failed to update the version.
I solved it by deleting the specific file and updating the version.
