### ISSUE TITLE
Feature Request: Allow for "updating" many-to-many intersect tables

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/Sql4Cds#361]
If you attempt to update a many-to-many intersect table, you get this error:

Cannot update many-to-many intersect entities: <tableName>
DELETE any unwanted records and then INSERT the correct values instead

Would be nice to either give the SQL to do the Insert and Delete, or just do it for the user.

**Comment by MarkMpn** [comment]
Good point, I should be able to remove this restriction in the next version.
