### ISSUE TITLE
Object Explorer is missing

### ISSUE THREAD

**Issue by blangero** [MarkMpn/Sql4Cds#362]
With XrmToolBox version: v1.2023.9.66 and SQL4CDS version: 7.5.2.0, I cannot find Object Explorer anymore.

**Comment by MarkMpn** [comment]
The window locations are now saved, currently the only way to reset it would be to close XrmToolBox, delete your settings file which would normally be at %appdata%\MscrmTools\XrmToolBox\Settings\MarkMpn.Sql4Cds.xml and restart XrmToolBox again. I'll look at adding a reset option into the settings page somewhere.

**Comment by blangero** [comment]
Thanks a lot @MarkMpn for the suggestion, I tried to compare a corrupted setting file with a working one, and found that delete the 'DockLayout' section would help to recover Object Explorer without losing other settings.
