### ISSUE TITLE
Unhandled expression type:

### ISSUE THREAD

**Issue by ivanarnhemongithub** [MarkMpn/Sql4Cds#365]
My query worked before and now throws this error Unhandled expression type:

**Comment by MarkMpn** [comment]
Can you share the query please?

**Comment by ivanarnhemongithub** [comment]
Hello,

Here it is: the problem is the part with the not in clause
DECLARE @week_num varchar(100)
SET @week_num = '2023 - 33'
select per.psa_name as weeknummer, emp.internalemailaddress as medewerker, per.psa_startdate,psa_enddate, gebruiker.psa_istimecardusername
from systemuser as emp
inner join hrm_employee ON emp.systemuserid = hrm_employee.hrm_crmuser
inner join psa_psauser as gebruiker ON emp.systemuserid = gebruiker.psa_employee
inner join psa_bookingperiod as per on per.psa_name = @week_num
where  emp.islicensed =1
and gebruiker.psa_istimecardusername ='Ja. Volledig boeken verplicht.'
and per.psa_name = @week_num
and per.psa_legalentity='2c913d44-f6ca-e811-a96f-000d3a2bc5c1'
and (hrm_employee.hrm_contracteffectivedate < per.psa_startdate or  hrm_employee.hrm_contracteffectivedate is null)
and (hrm_employee.hrm_contractenddate > per.psa_enddate or hrm_employee.hrm_contractenddate is null)
--and (hrm_employee.hrm_contracttype!='')
-- now the problem starts
and emp.systemuserid not in
(select  psa_timecard.psa_employee
from  psa_bookingperiod AS periode
inner join psa_timecard ON periode.psa_bookingperiodid = psa_timecard.psa_bookingperiod
where periode.psa_legalentity='2c913d44-f6ca-e811-a96f-000d3a2bc5c1'
and ***@***.******@***.***_num>
)
order by emp.internalemailaddress

Met vriendelijke groet,​​​​
​
Ineke van Arnhem
IT‑Medewerker
Niet aanwezig op: woe, don en vrijdagmiddag





Van: Mark Carrington ***@***.***>
Verzonden: maandag 2 oktober 2023 17:17
Aan: MarkMpn/Sql4Cds ***@***.***>
CC: Ineke van Arnhem | Kreston Van Herwijnen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [MarkMpn/Sql4Cds] Unhandled expression type: (Issue #365)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Can you share the query please?

**Comment by MarkMpn** [comment]
Thanks, unfortunately it looks like GitHub has corrupted the last part of the query, can you please try entering it via the web UI at https://github.com/MarkMpn/Sql4Cds/issues/365 rather than by email?

**Comment by ivanarnhemongithub** [comment]
(DECLARE @week_num varchar(100)
SET @week_num = '2023 - 39'
select per.psa_name as weeknummer, emp.internalemailaddress as medewerker, per.psa_startdate,psa_enddate, gebruiker.psa_istimecardusername
from systemuser as emp 
inner join hrm_employee ON emp.systemuserid = hrm_employee.hrm_crmuser
inner join psa_psauser as gebruiker ON emp.systemuserid = gebruiker.psa_employee
inner join psa_bookingperiod as per on per.psa_name = @week_num
where  emp.islicensed =1
and gebruiker.psa_istimecardusername ='Ja. Volledig boeken verplicht.' 
and per.psa_name = @week_num
and per.psa_legalentity='2c913d44-f6ca-e811-a96f-000d3a2bc5c1'
and (hrm_employee.hrm_contracteffectivedate < per.psa_startdate or  hrm_employee.hrm_contracteffectivedate is null)
and (hrm_employee.hrm_contractenddate > per.psa_enddate or hrm_employee.hrm_contractenddate is null)
--and (hrm_employee.hrm_contracttype!='')
and emp.systemuserid not in
(select  psa_timecard.psa_employee
from  psa_bookingperiod AS periode
inner join psa_timecard ON periode.psa_bookingperiodid = psa_timecard.psa_bookingperiod
where periode.psa_legalentity='2c913d44-f6ca-e811-a96f-000d3a2bc5c1'
and periode.psa_name=@week_num
)
order by emp.internalemailaddress

)

**Comment by ivanarnhemongithub** [comment]
correct issue is fixed perfect thenks
