### ISSUE TITLE
Unsupported data type reference: [MarkMpn.Sql4Cds.Engine.SqlEntityReference]

### ISSUE THREAD

**Issue by clintonbale** [MarkMpn/Sql4Cds#367]
When attempting to run the [sample from the blog](https://markcarrington.dev/2022/09/22/sql-4-cds-v7-released/#stored_procedures), the query gets an error related to the `CREATELOOKUP` and the  `SqlEntityReference` type.

Query:
```tsql
DECLARE @contactid AS [MarkMpn.Sql4Cds.Engine.SqlEntityReference] = CREATELOOKUP('contact', '{myid}');
EXECUTE RetrieveRecordChangeHistory @Target = @contactid;
```

Error:

`Unsupported data type reference: [MarkMpn.Sql4Cds.Engine.SqlEntityReference]`

---
- Deployment: Online
- DB Version: 9.2.23093.196
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.9.66
- Tool Version: 7.6.0.0

**Comment by MarkMpn** [comment]
Thanks, I need to update the blog. I made it easier to use this data type in recent updates so you can now use it as:

```sql
DECLARE @contactid AS EntityReference = CREATELOOKUP('contact', '{myid}');
EXECUTE RetrieveRecordChangeHistory @Target = @contactid;
```
