### ISSUE TITLE
Use Bulk Delete option - start time off by time zone

### ISSUE THREAD

**Issue by akaskela** [MarkMpn/Sql4Cds#380]
Hi @MarkMpn, thanks for the awesome tool. I noticed a minor issue when I tried to delete records with the Use Bulk Delete operations checked. The bulk delete process is created correctly but the start time doesn't handle timezones correctly. My user is EST (UTC-4) and when I run the delete at 12:00 it's created with a scheduled time of 16:00.

**Comment by MarkMpn** [comment]
Is it possible that your Windows setup is on a different time zone from the Dataverse user profile, e.g. Windows is on EST but you're connecting with an application user which is set to UTC?

At the moment it's using `DateTime.Now` to schedule it, which follows the Microsoft sample code. I can try changing it to `DateTime.UtcNow` and see if that works, but it's worth checking if your user profile settings are consistent as well.
