### ISSUE TITLE
Cannot update a record

### ISSUE THREAD

**Issue by Edeliweiss** [MarkMpn/Sql4Cds#385]
Hello, 
I faced an issue during an update of a person, (making it deactivated) I received these errors:

1. updating status code and state code  `The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
`

or 

2. updating only one field `The request channel timed out while waiting for a reply after 00:01:59.9279208. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
The HTTP request to 'https:/{env}/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.49.3165' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
The operation has timed out
` 
I have no problem with any other record of this type. It is deactivated and activated without any problems.

Deployment: Online
DB Version: 9.2.49.3165
Connection Controls Version: 1.2023.6.56
XrmToolBox Version: 1.2023.9.66
Tool Version: 7.6.1.0

**Comment by MarkMpn** [comment]
This doesn’t look like anything specific to do with SQL 4 CDS. If an update to a record is taking over 2 minutes it is likely due to either some long-running plugins or a temporary network issue.

**Comment by MarkMpn** [comment]
This doesn’t look like anything specific to do with SQL 4 CDS. If an update to a record is taking over 2 minutes it is likely due to either some long-running plugins or a temporary network issue.

**Comment by Edeliweiss** [comment]
The strange thing is that I ran it with ByPass Custom Execution. As I understand it must execute without launching the plugins. And the error persists on different days at different hours.
