### ISSUE TITLE
Querying a table with more than 300,000 records does not finish

### ISSUE THREAD

**Issue by hiroyuki0415** [MarkMpn/Sql4Cds#387]
Querying a table with more than 300,000 records does not finish

```sql
SELECT count(*)
FROM   your_table; --300,000 over


```

When I run this SQL, the following appears forever: 
```
partitioning your_table (100%)...
```

Thanks in advance for your support.

**Comment by MarkMpn** [comment]
Were you able to get this query to return you a result? If not, are you able to share the `createdon` dates of the records to help me diagnose it? I'm hoping to get a new release out shortly and I'd like to make sure I include a fix for any bug that exists around this area at the same time.

**Comment by hiroyuki0415** [comment]
Thank you for your quick reply.

```sql
SELECT
    createdon,
    count(*)
FROM
    vds_houjin_goto_no_cost
GROUP BY createdon
```

[createdon_groupby.csv](https://github.com/MarkMpn/Sql4Cds/files/13398020/createdon_groupby.csv)
