### ISSUE TITLE
[Suggestion] `Copy as JSON` in context menu when selected row/rows

### ISSUE THREAD

**Issue by rafek1241** [MarkMpn/Sql4Cds#39]
Related picture:
![image](https://user-images.githubusercontent.com/9272027/102093477-815b0180-3e21-11eb-85c5-62187a87b88c.png)
There could be `Copy as JSON` button.

**Comment by MarkMpn** [comment]
What data would be useful to have in that JSON string? Where would you be looking to use it?

**Comment by rafek1241** [comment]
To share this data in a simple text file or within a JIRA. When you're copying rows - how do you share it? Are you using Excel?

**Comment by MarkMpn** [comment]
I think most people are using Excel. I'll consider it for a future release though.

**Comment by rafek1241** [comment]
I'm closing the issue because excel resolve that thing.
