### ISSUE TITLE
Cross thread error when executing

### ISSUE THREAD

**Issue by rappen** [MarkMpn/Sql4Cds#4]
Opened SQL4CDS from FXB, hit Execute, and got this:
`Cross-thread operation not valid: Control 'toolStripMenu' accessed from a thread other than the thread it was created on.`

![image](https://user-images.githubusercontent.com/2572253/75113127-01259e80-564b-11ea-8543-455fd7cb15dd.png)

---
- Deployment: Online
- DB Version: 9.1.0.13533
- XTB Version: 1.2020.2.37
- Tool Version: 1.0.9.0

**Comment by MarkMpn** [comment]
I can't reproduce this yet. Does it happen consistently when you try to execute a query that's been converted from FXB? How about for queries you write directly in SQL 4 CDS?
