### ISSUE TITLE
SQL 4 CDS reserved keywords

### ISSUE THREAD

**Issue by khanhprp** [MarkMpn/Sql4Cds#402]
Hi Mark, hope you are doing great! 

I am using SQL 4 CDS, the tool is powerful! 
However I am not sure how to work with reserve keyword in query. Need to query/ update 'from', 'to' fields from email.

Previously it was on version 7.0.3,0 and square brackets worked fine. Now it's 8.0.0.0 and not working:
![image](https://github.com/MarkMpn/Sql4Cds/assets/152480015/9262ff88-b254-4df2-ac33-af919ef7e055)

Please kindly help on this, thank you a lot~

**Comment by MarkMpn** [comment]
Thanks, I'll take a look. In the meantime you can reinstall a previous version from the tool library so you can continue working.

**Comment by khanhprp** [comment]
[heart]         Grace Vu (Tek Experts) reacted to your message:
________________________________
