### ISSUE TITLE
Issue with new version 8.0.0.0

### ISSUE THREAD

**Issue by tobarishkarloff** [MarkMpn/Sql4Cds#413]
I installed the new version for SQL 4 CDS in the xrmtoolbox.

I have the newest version of xrmtoolbox installed

when I try to open the entities with the SQL 4 CDS I get an error message and when I try to run a query I get the same error.

With the version before I didn't have those error messages
![SQL4CDSerror2](https://github.com/MarkMpn/Sql4Cds/assets/155756319/d1ccad9e-c708-4ed9-aa85-b5a0f2613db4)
![SQL4CDSerror1](https://github.com/MarkMpn/Sql4Cds/assets/155756319/ad89b512-7adf-4d83-a636-6811f726fd00)

Thank you.

Regards

**Comment by MarkMpn** [comment]
It sounds like you might have an old version of the Microsoft.Xrm.Sdk assembly somewhere that XrmToolBox is picking up. You could try downloading a fresh copy of XrmToolBox to a new folder and see if that resolves the problem, or check for copies of Microsoft.Xrm.Sdk.dll in the %AppData%\MscrmTools\XrmToolBox\Plugins folder and delete them

**Comment by tobarishkarloff** [comment]
Thanks for your answer

I reset my XrmToolBox to default and I got the same results
https://www.xrmtoolbox.com/documentation/for-users/reset-xrmtoolbox-installation/

**Comment by MarkMpn** [comment]
Can you look under Configuration > Settings > Assemblies and check the version of the Microsoft.Xrm.Sdk assembly? It should be 9.2.49.3165 or higher. If it's lower there must be another version somewhere on your PC that XrmToolBox is picking up incorrectly.

**Comment by tobarishkarloff** [comment]
Hi I checked and I have these values

[image: imagen.png]

**Comment by MarkMpn** [comment]
The image didn't come through, can you please try adding the details at https://github.com/MarkMpn/Sql4Cds/issues/413 rather than by email?
