### ISSUE TITLE
Parsing XML Attribute Using XPath

### ISSUE THREAD

**Issue by tony-mykhaylovsky-va** [MarkMpn/Sql4Cds#419]
Hi Mark,

Trying to figure out how to get a contact entity's system form's Display Order from XML.

```sql
select name, formxml, cast(formxml as xml)
,cast(formxml as xml).value('string(/form/DisplayConditions/@Order)', 'nvarchar(50)') 
from systemform
where objecttypecode = 'contact' and type = 2 --Main
```

Error:
Unhandled return type System.String

I tried building the XPath string using below online tool; however, unsure how to select this output of in SQL 4 CDS
https://www.freeformatter.com/xpath-tester.html#before-output

Thank you for the help

**Comment by MarkMpn** [comment]
The `.value()` function currently only supports binary data to allow base64 decoding. I can look at extending this in the next update.
