### ISSUE TITLE
email entity column "from", "to" not queryable

### ISSUE THREAD

**Issue by TobiasKoller** [MarkMpn/Sql4Cds#421]
I would like to query the email entity and filter by column "from" and "to".
But these are keywords which doesnt work. I'm also not able to use [] to mask the column-names.

Is this even possible?

by the way: this tool is the best I've ever used within the toolbox. No idea how I could live without it before ;-)

**Comment by TobiasKoller** [comment]
great! thank you so much for this tool!

**Comment by MarkMpn** [comment]
Closing as a duplicate of #402
