### ISSUE TITLE
Select TOP 1 not being respected in Inner query

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/Sql4Cds#429]
Was trying to cleanup some duplicate records.

Ran this query:

![image](https://github.com/MarkMpn/Sql4Cds/assets/9728423/da4aef30-c206-471b-af1d-c1cafe38d6f6)

Then went and attempted to deactivate the first duplicate record with this query:

![image](https://github.com/MarkMpn/Sql4Cds/assets/9728423/2bdbe49e-7b6d-430e-bbd8-b463431a0a7e)

but as you can see, it updated 2 records, rather than one.  Looks to only be an issue with Top 1.  Top 2 or more worked...

---
- Deployment: Online
- DB Version: 9.2.23122.208
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68
- Tool Version: 8.0.0.0

**Comment by MarkMpn** [comment]
Thanks for the details - I’ve got a fix for this now but it might still be a while until the next release while I’m working on other areas. In the meantime you should get the expected results if you replace `IN` with `=` when you only want to update a single record.
