### ISSUE TITLE
Unable to locate dependency

### ISSUE THREAD

**Issue by Jonathanmsharp** [MarkMpn/Sql4Cds#43]
Since installing the lastest update this error pops up whenever I try to open the plugin.  I tried uninstalling it and readding it but to no avail.  

![Screenshot 2020-12-18 091028](https://user-images.githubusercontent.com/76222345/102641438-ee67e300-4110-11eb-914a-456693fe702c.png)

**Comment by MarkMpn** [comment]
What version of XrmToolBox are you running?
This file `ScintillaNET.dll` should be present in your main XrmToolBox folder - can you check if you can see it there?

**Comment by Jonathanmsharp** [comment]
It is not in there.  Where can i find it?

**Comment by MarkMpn** [comment]
What version of a XrmToolBox are you running?

**Comment by Jonathanmsharp** [comment]
I hadn't updated Xrm in a while, now that I have the newest version its
working great.  Thanks
