### ISSUE TITLE
Can't open Sql4Cds after upgrading to 8.0

### ISSUE THREAD

**Issue by jxs0900** [MarkMpn/Sql4Cds#432]
Sorry to bother you with this but i've tried everything I can think of.  I get the error "An error occured when trying to display this tool: Exception has been thrown by the target of an invocation"
![image](https://github.com/MarkMpn/Sql4Cds/assets/8445048/f2d653a1-dd1c-46fc-a710-578abf387009)

![image](https://github.com/MarkMpn/Sql4Cds/assets/8445048/7e52319d-0e41-4385-a437-e19483c9c30f)

**Comment by jxs0900** [comment]
I apologize, I tried everything EXCEPT reinstalling XrmToolbox.  I did that and Sql4Cds is working now.

**Comment by MarkMpn** [comment]
Could you please take a look in the %appdata%\MscrmTools\XrmToolBox\Settings and %appdata%\MscrmTools\XrmToolBox\Logs folders - there should be a settings file and a log file for MarkMpn.Sql4Cds, could you post them both please?
