### ISSUE TITLE
The 'RetrieveMultiple' method does not support entities of type 'optionset'

### ISSUE THREAD

**Issue by sybaris** [MarkMpn/Sql4Cds#436]
Hi,

The following SQL "select top 10 * from optionset" returns an error "The 'RetrieveMultiple' method does not support entities of type 'optionset'. MessageProcessorCache returned MessageProcessor.Empty."

![image](https://github.com/MarkMpn/Sql4Cds/assets/11009997/99e0b8ee-2431-44a8-a657-d76e1f2c798d)

Regards
Sybaris

**Comment by MarkMpn** [comment]
Correct, this table appears to be impossible to retrieve any values from. Global optionsets are available through the `metadata` schema` though if that helps.
