### ISSUE TITLE
 Object Browser is missing in SQL 4 CDS

### ISSUE THREAD

**Issue by lanadcwp** [MarkMpn/Sql4Cds#439]
The Object Browser in the left pane is missing in SQL 4 CDS after installing SQL 4 CDS version 8.0.0.
Thanks

**Comment by MarkMpn** [comment]
Can you go to Settings > Editor and click "Reset Tool Windows"?

If that doesn't work, please review the instructions in #362

**Comment by lanadcwp** [comment]
Thank you, Mark!
It worked.


Regards,

Lana Goldenberg ~  NYC DCWP
t: 212-436-0053|nyc.gov/dcwp
From: Mark Carrington ***@***.***>
Sent: Tuesday, March 12, 2024 1:35 PM
To: MarkMpn/Sql4Cds ***@***.***>
Cc: Goldenberg, Lana (DCWP) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [MarkMpn/Sql4Cds] Object Browser is missing in SQL 4 CDS (Issue #439)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.  Forward suspect email to ***@***.******@***.***> as an attachment (Click the More button, then forward as attachment).


Can you go to Settings > Editor and click "Reset Tool Windows"?

If that doesn't work, please review the instructions in #362<https://github.com/MarkMpn/Sql4Cds/issues/362>

-

**Comment by lanadcwp** [comment]
Thanks a lot, @MarkMpn !
It worked.

❤️
