### ISSUE TITLE
Incorrect Filtering on columns

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/Sql4Cds#440]
If I run this query:
``` sql
SELECT top 10 FullName, mad_ownerusername, contact.mad_specssalesrepusername
FROM mad_specsengagementletter
INNER JOIN contact ON mad_specsengagementletter.mad_client = contact.contactid
WHERE mad_ownerusername <> contact.mad_specssalesrepusername AND contact.mad_specssalesrepusername IS NULL
```
I get 0 results, but if I run this query where I remove the not equal to:

``` sql
SELECT top 10 FullName, mad_ownerusername, contact.mad_specssalesrepusername
FROM mad_specsengagementletter
INNER JOIN contact ON mad_specsengagementletter.mad_client = contact.contactid
WHERE contact.mad_specssalesrepusername IS NULL
```
I get 10+ results, and for the records that are returned, mad_ownerusername is not null.  mad_ownerusername  and mad_specssalesrepusername  are both FX Calculated columns that are just the user name of the owning user...

(using SQL 4 CDS 8.0.0.0)

**Comment by MarkMpn** [comment]
SQL 4 CDS follows the [ANSI NULL behavior](https://learn.microsoft.com/en-us/sql/t-sql/statements/set-ansi-nulls-transact-sql?view=sql-server-ver16) where `<any value> <> NULL` gives an `UNKNOWN` result which is filtered out by the WHERE clause.

Because of this, `WHERE mad_ownerusername <> contact.mad_specssalesrepusername AND contact.mad_specssalesrepusername IS NULL` is an impossible `WHERE` clause and it will always return 0 records.

**Comment by daryllabar** [comment]
So is `WHERE mad_ownerusername <> contact.mad_specssalesrepusername OR contact.mad_specssalesrepusername IS NULL` more likely what I want?

**Comment by MarkMpn** [comment]
Yes, assuming `mad_ownerusername` is guaranteed to be non-null. If that could be null as well you’ll need to extend it to:

```sql
WHERE mad_ownerusername <> contact.mad_specssalesrepusername OR
mad_ownerusername IS NOT NULL AND contact.mad_specssalesrepusername IS NULL OR
mad_ownerusername IS NULL AND contact.mad_specssalesrepusername IS NOT NULL
```

You can also use the newer [`IS DISTINCT FROM`](https://learn.microsoft.com/en-us/sql/t-sql/queries/is-distinct-from-transact-sql?view=sql-server-ver16) syntax:

```sql
WHERE mad_ownerusername IS DISTINCT FROM contact.mad_specsalesrepusername
```

This syntax isn’t currently supported in the TDS Endpoint however.
