### ISSUE TITLE
SQL 4 CDS ability to change default font size in window where code is written

### ISSUE THREAD

**Issue by SSavlowitz** [MarkMpn/Sql4Cds#444]
Hi Mark,
Per your blog response I am opening this new ticket.
My eyes are going and in all my SQL environments I have been able to change the default size of the font used when creating scripts.  i think this would be a great option for your tool as well.
Thank you
Scott

**Comment by SSavlowitz** [comment]
Thank you Mark,
I should get prompted when the update has been released?
Thanks again.
Scott

**Comment by MarkMpn** [comment]
Yes, XrmToolBox will show you a prompt to upgrade when it is available.

**Comment by SSavlowitz** [comment]
Awesome, thanks for the update!
