### ISSUE TITLE
Support for SSMS version 20.0

### ISSUE THREAD

**Issue by dancohenenterprise** [MarkMpn/Sql4Cds#447]
Thank you for maintaining this software.  Quite helpful.

SSMS Version 20.0 was released on 3/19/24;  
https://learn.microsoft.com/en-us/sql/ssms/release-notes-ssms

Will Sql4Cds v8.0.0 work with SSMS Version 20.0 or will a new release be required to support SSMS Version 20.0?

in the Sql4Cds v8.0.0 Releases, the latest MSI installer seems to be for SSMS 19.
https://github.com/MarkMpn/Sql4Cds/releases/tag/v8.0.0
MarkMpn.Sql4Cds.SSMS.19.Setup.msi 

Please advise.

**Comment by MarkMpn** [comment]
The existing releases won’t work in SSMS 20 - support for this is already complete in the next version which will hopefully be released in the next couple of weeks.

**Comment by dancohenenterprise** [comment]
Amazing, thanks
