### ISSUE TITLE
Exception is thrown when you are typing a SQL query and the typing intellisence kicks in

### ISSUE THREAD

**Issue by aylosx** [MarkMpn/Sql4Cds#45]
This wasn't happening until I updated the plug-in to the latest version 3.1.0.0. 

When you are in the editor and typing a SQL query and the intellisense kicks in to find (filter) an entity or an attribute the exception is thrown. That happens on every character you are keying in. I uninstalled the plug-in and re-installed it but it didn't fix the issue. Is it me only ? 

![image](https://user-images.githubusercontent.com/6900439/103892220-1c728e80-50e3-11eb-9ad9-2f5b8d06e23a.png)

The exception details are as follows: 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at MarkMpn.Sql4Cds.Autocomplete.AttributeAutocompleteItem..ctor(AttributeMetadata attribute, IAttributeMetadataCache metadata, Int32 replaceLength)
   at MarkMpn.Sql4Cds.Autocomplete.<>c__DisplayClass3_0.<GetSuggestions>b__30(IGrouping`2 g)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at MarkMpn.Sql4Cds.Autocomplete.GetSuggestions(String text, Int32 pos)
   at MarkMpn.Sql4Cds.SqlQueryControl.<>c__DisplayClass47_0.<CreateSqlEditor>b__3(Object s, DwellEventArgs e)
   at ScintillaNET.Scintilla.OnDwellStart(DwellEventArgs e)
   at ScintillaNET.Scintilla.WmReflectNotify(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MarkMpn** [comment]
Can you reproduce this on other environments? I can't get this error to happen on my environments.

The error seems to indicate there is a virtual attribute on the `account` entity that relates to another attribute that doesn't exist. Could you try running the following query and post the results?

```sql
SELECT   logicalname,
         attributeof
FROM     attribute
WHERE    entitylogicalname = 'account'
ORDER BY logicalname;
```

**Comment by aylosx** [comment]
Hi Mark 

here is the list of attributes - it could be potentially related to my customer's environments - I also recently had an issue with my code generator and I had to update it to the latest CrmSvcUtil because I was getting some object reference errors from the old CrmSvcUtil. I tried in my own instances (vanilla d365) and have no issues. It is only in my customer instances I think - something that is loaded there could be causing the error.  

  | logicalname | attributeof
-- | -- | --
  | accountcategorycode |  
  | accountcategorycodename | accountcategorycode
  | accountclassificationcode |  
  | accountclassificationcodename | accountclassificationcode
  | accountid |  
  | accountnumber |  
  | accountratingcode |  
  | accountratingcodename | accountratingcode
  | address1_addressid |  
  | address1_addresstypecode |  
  | address1_addresstypecodename | address1_addresstypecode
  | address1_city |  
  | address1_composite |  
  | address1_country |  
  | address1_county |  
  | address1_fax |  
  | address1_freighttermscode |  
  | address1_freighttermscodename | address1_freighttermscode
  | address1_latitude |  
  | address1_line1 |  
  | address1_line2 |  
  | address1_line3 |  
  | address1_longitude |  
  | address1_name |  
  | address1_postalcode |  
  | address1_postofficebox |  
  | address1_primarycontactname |  
  | address1_shippingmethodcode |  
  | address1_shippingmethodcodename | address1_shippingmethodcode
  | address1_stateorprovince |  
  | address1_telephone1 |  
  | address1_telephone2 |  
  | address1_telephone3 |  
  | address1_upszone |  
  | address1_utcoffset |  
  | address2_addressid |  
  | address2_addresstypecode |  
  | address2_addresstypecodename | address2_addresstypecode
  | address2_city |  
  | address2_composite |  
  | address2_country |  
  | address2_county |  
  | address2_fax |  
  | address2_freighttermscode |  
  | address2_freighttermscodename | address2_freighttermscode
  | address2_latitude |  
  | address2_line1 |  
  | address2_line2 |  
  | address2_line3 |  
  | address2_longitude |  
  | address2_name |  
  | address2_postalcode |  
  | address2_postofficebox |  
  | address2_primarycontactname |  
  | address2_shippingmethodcode |  
  | address2_shippingmethodcodename | address2_shippingmethodcode
  | address2_stateorprovince |  
  | address2_telephone1 |  
  | address2_telephone2 |  
  | address2_telephone3 |  
  | address2_upszone |  
  | address2_utcoffset |  
  | aging30 |  
  | aging30_base |  
  | aging60 |  
  | aging60_base |  
  | aging90 |  
  | aging90_base |  
  | businesstypecode |  
  | businesstypecodename | businesstypecode
  | createdby |  
  | createdbyexternalparty |  
  | createdbyexternalpartyname | createdbyexternalparty
  | createdbyexternalpartyyominame | createdbyexternalparty
  | createdbyname | createdby
  | createdbyyominame | createdby
  | createdon |  
  | createdonbehalfby |  
  | createdonbehalfbyname | createdonbehalfby
  | createdonbehalfbyyominame | createdonbehalfby
  | creditlimit |  
  | creditlimit_base |  
  | creditonhold |  
  | creditonholdname | creditonhold
  | customersizecode |  
  | customersizecodename | customersizecode
  | customertypecode |  
  | customertypecodename | customertypecode
  | defaultpricelevelid |  
  | defaultpricelevelidname | defaultpricelevelid
  | description |  
  | donotbulkemail |  
  | donotbulkemailname | donotbulkemail
  | donotbulkpostalmail |  
  | donotbulkpostalmailname | donotbulkpostalmail
  | donotemail |  
  | donotemailname | donotemail
  | donotfax |  
  | donotfaxname | donotfax
  | donotphone |  
  | donotphonename | donotphone
  | donotpostalmail |  
  | donotpostalmailname | donotpostalmail
  | donotsendmarketingmaterialname | donotsendmm
  | donotsendmm |  
  | emailaddress1 |  
  | emailaddress2 |  
  | emailaddress3 |  
  | entityimage | entityimageid
  | entityimage_timestamp | entityimageid
  | entityimage_url | entityimageid
  | entityimageid |  
  | exchangerate |  
  | fax |  
  | followemail |  
  | followemailname | followemail
  | ftpsiteurl |  
  | grg_accountcheckstatus |  
  | grg_accountcheckstatusname | grg_accountcheckstatus
  | grg_accountexecutive |  
  | grg_accountexecutivename | grg_accountexecutive
  | grg_accountexecutiveyominame | grg_accountexecutive
  | grg_accountopeningpurpose |  
  | grg_accountopeningpurposecompleted |  
  | grg_accountopeningpurposecompletedname | grg_accountopeningpurposecompleted
  | grg_accountopeningpurposename | grg_accountopeningpurpose
  | grg_accountpurposeother |  
  | grg_accountreferredbyid |  
  | grg_accountreferredbyidname | grg_accountreferredbyid
  | grg_accountreferredbyidyominame | grg_accountreferredbyid
  | grg_accountstatusreason |  
  | grg_accountstatusreasonname | grg_accountstatusreason
  | grg_accountsubstatusreason |  
  | grg_accountsubstatusreasonname | grg_accountsubstatusreason
  | grg_accounttype |  
  | grg_accounttypename | grg_accounttype
  | grg_additionalcontact |  
  | grg_additionalinformation |  
  | grg_address1_countryid |  
  | grg_address1_countryidname | grg_address1_countryid
  | grg_address2_countryid |  
  | grg_address2_countryidname | grg_address2_countryid
  | grg_aeintroducer |  
  | grg_aeintroducername | grg_aeintroducer
  | grg_aeintroduceryominame | grg_aeintroducer
  | grg_allbulletfieldscomplete |  
  | grg_allbulletfieldscompletename | grg_allbulletfieldscomplete
  | grg_alltrunarrativefieldscomplete |  
  | grg_alltrunarrativefieldscompletename | grg_alltrunarrativefieldscomplete
  | grg_amlriskrating |  
  | grg_amlriskratingname | grg_amlriskrating
  | grg_applicablefrn |  
  | grg_applicationcompleted |  
  | grg_applicationcompleteddate |  
  | grg_applicationcompletedname | grg_applicationcompleted
  | grg_applicationformsent |  
  | grg_applicationformsentdate |  
  | grg_applicationformsentname | grg_applicationformsent
  | grg_artnershipacc1contact |  
  | grg_artnershipacc1contactname | grg_artnershipacc1contact
  | grg_artnershipacc1contactyominame | grg_artnershipacc1contact
  | grg_bacspaymentchargescurrency |  
  | grg_bacspaymentchargescurrencyname | grg_bacspaymentchargescurrency
  | grg_bacspaymentchargesdealer |  
  | grg_bacspaymentchargesdealername | grg_bacspaymentchargesdealer
  | grg_bacspaymentchargesonline |  
  | grg_bacspaymentchargesonlinename | grg_bacspaymentchargesonline
  | grg_bacspaymentchargesownership |  
  | grg_bacspaymentchargesownershipname | grg_bacspaymentchargesownership
  | grg_balancesheettotalamount |  
  | grg_balancesheettotalamount_base |  
  | grg_bankaccountnumber |  
  | grg_bankname |  
  | grg_bankzippostalcode |  
  | grg_bilateralmarginagreement |  
  | grg_bilateralmarginagreementname | grg_bilateralmarginagreement
  | grg_bulletcallrequired |  
  | grg_bulletcallrequiredname | grg_bulletcallrequired
  | grg_bulletprimarykey |  
  | grg_buysellcomplete |  
  | grg_buysellcompletename | grg_buysellcomplete
  | grg_bvdid |  
  | grg_categorisation |  
  | grg_categorisationname | grg_categorisation
  | grg_chapspaymentchargescurrency |  
  | grg_chapspaymentchargescurrencyname | grg_chapspaymentchargescurrency
  | grg_chapspaymentchargesdealer |  
  | grg_chapspaymentchargesdealername | grg_chapspaymentchargesdealer
  | grg_chapspaymentchargesonline |  
  | grg_chapspaymentchargesonlinename | grg_chapspaymentchargesonline
  | grg_chapspaymentchargesownership |  
  | grg_chapspaymentchargesownershipname | grg_chapspaymentchargesownership
  | grg_charitynumber |  
  | grg_clientcategorisation |  
  | grg_clientcategorisationname | grg_clientcategorisation
  | grg_clientclassificationdate |  
  | grg_clientcode |  
  | grg_clientsegment |  
  | grg_clientsegmentname | grg_clientsegment
  | grg_clientstatus |  
  | grg_clientstatusname | grg_clientstatus
  | grg_clienttier |  
  | grg_clienttiername | grg_clienttier
  | grg_codeaccount |  
  | grg_codeaccountname | grg_codeaccount
  | grg_codeddate |  
  | grg_codeddatelocal |  
  | grg_commissionpercentage |  
  | grg_commissiontype |  
  | grg_commissiontypename | grg_commissiontype
  | grg_companylegalname |  
  | grg_companyregistrationnumber |  
  | grg_companytype |  
  | grg_companytypename | grg_companytype
  | grg_competitors |  
  | grg_compid |  
  | grg_corporatesectornacecode |  
  | grg_corporatesectornacecodename | grg_corporatesectornacecode
  | grg_countriesservedcompleted |  
  | grg_countriesservedcompletedname | grg_countriesservedcompleted
  | grg_data8_telephone1_tps |  
  | grg_data8_telephone1_tpsname | grg_data8_telephone1_tps
  | grg_data8_telephone2_tps |  
  | grg_data8_telephone2_tpsname | grg_data8_telephone2_tps
  | grg_data8_tpsstatus |  
  | grg_dealer |  
  | grg_dealerintroducer |  
  | grg_dealerintroducername | grg_dealerintroducer
  | grg_dealerintroduceryominame | grg_dealerintroducer
  | grg_dealername | grg_dealer
  | grg_dealeryominame | grg_dealer
  | grg_delegatedemirreporting |  
  | grg_delegatedemirreportingname | grg_delegatedemirreporting
  | grg_delegatedemirreportingstartdate |  
  | grg_delegatedoptoutdate |  
  | grg_digitalpromotionmethod |  
  | grg_digitalpromotionmethodname | grg_digitalpromotionmethod
  | grg_emirstatus |  
  | grg_emirstatusname | grg_emirstatus
  | grg_firsttradedate |  
  | grg_firsttradediscount |  
  | grg_firsttransferperiod |  
  | grg_firsttransferperiodname | grg_firsttransferperiod
  | grg_forwarddeposit |  
  | grg_forwarddepositname | grg_forwarddeposit
  | grg_frequencyoftrade |  
  | grg_frequencyoftradename | grg_frequencyoftrade
  | grg_furthestvaluedate |  
  | grg_fwddepositdiscount |  
  | grg_fwdtradinglimit |  
  | grg_fxrange |  
  | grg_fxrangename | grg_fxrange
  | grg_fxturnover |  
  | grg_fxturnovername | grg_fxturnover
  | grg_grmaccountopeningdocument_name | grg_grmaccountopeningdocument
  | grg_grmaccountopeningdocumentanchor |  
  | grg_grmformsubmissiondate |  
  | grg_grmsuitabilitydocument_name | grg_grmsuitabilitydocument
  | grg_grmsuitabilitydocumentanchor |  
  | grg_grmsuitabilityreceptiondate |  
  | grg_grmsuitabilityreviewerid |  
  | grg_grmsuitabilityrevieweridname | grg_grmsuitabilityreviewerid
  | grg_grmsuitabilityrevieweridyominame | grg_grmsuitabilityreviewerid
  | grg_grmsuitabilitystatus |  
  | grg_grmsuitabilitystatusname | grg_grmsuitabilitystatus
  | grg_grossmargin |  
  | grg_grossprofit |  
  | grg_hearaboutus |  
  | grg_hearaboutusname | grg_hearaboutus
  | grg_holdingoffice |  
  | grg_holdingofficename | grg_holdingoffice
  | grg_howdidyouhearaboutus |  
  | grg_howdidyouhearaboutusother |  
  | grg_ib |  
  | grg_iban |  
  | grg_ibcode |  
  | grg_ibgross |  
  | grg_ibgrossname | grg_ibgross
  | grg_ibindustry |  
  | grg_ibindustryname | grg_ibindustry
  | grg_ibname | grg_ib
  | grg_inbullet |  
  | grg_inbulletname | grg_inbullet
  | grg_incorporationcountryid |  
  | grg_incorporationcountryidname | grg_incorporationcountryid
  | grg_incorporationdate |  
  | grg_industry |  
  | grg_industryname | grg_industry
  | grg_institutionalinvestor |  
  | grg_institutionalinvestorname | grg_institutionalinvestor
  | grg_integrationtoggle |  
  | grg_intlapproved |  
  | grg_intlapprovedname | grg_intlapproved
  | grg_introducer |  
  | grg_introducername | grg_introducer
  | grg_invitationstatus |  
  | grg_invitationstatusname | grg_invitationstatus
  | grg_isauthorisedorregulated |  
  | grg_isauthorisedorregulatedname | grg_isauthorisedorregulated
  | grg_iscorporate |  
  | grg_iscorporatename | grg_iscorporate
  | grg_isprincipleaddress |  
  | grg_isprincipleaddressname | grg_isprincipleaddress
  | grg_jointapplication |  
  | grg_jointapplicationname | grg_jointapplication
  | grg_lastaccountreferraldate |  
  | grg_lastactivity |  
  | grg_lastleadreferraldate |  
  | grg_lasttpscheck |  
  | grg_lasttradedate |  
  | grg_leadoriginid |  
  | grg_leadoriginidname | grg_leadoriginid
  | grg_legacyaccountid |  
  | grg_legacyaccountidname | grg_legacyaccountid
  | grg_legacyaccountidyominame | grg_legacyaccountid
  | grg_legalentityid |  
  | grg_legalentityidname | grg_legalentityid
  | grg_leiexpirydate |  
  | grg_leinumber |  
  | grg_leiregisteredcountry |  
  | grg_leiregisteredcountryname | grg_leiregisteredcountry
  | grg_linktoemployee |  
  | grg_linktoemployeename | grg_linktoemployee
  | grg_maindourceid |  
  | grg_maindourceidname | grg_maindourceid
  | grg_marketingcampaign |  
  | grg_marketingcampaignname | grg_marketingcampaign
  | grg_marketingoptin |  
  | grg_marketingoptinname | grg_marketingoptin
  | grg_maximumtradescommissionpaidon |  
  | grg_nameoftheemployeelinkedwiththepartner |  
  | grg_nameoftheemployeelinkedwiththepartnername | grg_nameoftheemployeelinkedwiththepartner
  | grg_nameoftheemployeelinkedwiththepartneryominame | grg_nameoftheemployeelinkedwiththepartner
  | grg_natureofbusiness |  
  | grg_natureofthelinktoemployee |  
  | grg_natureofthelinktoemployeename | grg_natureofthelinktoemployee
  | grg_netgross |  
  | grg_netgrossname | grg_netgross
  | grg_netturnoveramount |  
  | grg_netturnoveramount_base |  
  | grg_npb |  
  | grg_npbname | grg_npb
  | grg_numberofyearsactive |  
  | grg_officeid |  
  | grg_officeidname | grg_officeid
  | grg_onboardeddate |  
  | grg_onboarderid |  
  | grg_onboarderidname | grg_onboarderid
  | grg_onboarderidyominame | grg_onboarderid
  | grg_onboardingdecision |  
  | grg_onboardingdecisiondate |  
  | grg_onboardingdecisionname | grg_onboardingdecision
  | grg_onboardingnotes |  
  | grg_onfirsttradevolumeexceeding |  
  | grg_onlinesignupprogress |  
  | grg_onmargincall |  
  | grg_onmargincallname | grg_onmargincall
  | grg_otherindustry |  
  | grg_otherinformationregardinglinktogrgemploye |  
  | grg_otherjobtitle |  
  | grg_otmfacility |  
  | grg_otmfacilityname | grg_otmfacility
  | grg_otmincrement |  
  | grg_otmincrementpercent |  
  | grg_otmincrementpercentname | grg_otmincrementpercent
  | grg_otmlimit |  
  | grg_otmstructure |  
  | grg_overriddencreatedby |  
  | grg_overriddenmodifiedby |  
  | grg_overriddenmodifiedon |  
  | grg_ovmpercentage |  
  | grg_ownfundsamount |  
  | grg_ownfundsamount_base |  
  | grg_paidbyclientbacs |  
  | grg_paidbyclientbacsname | grg_paidbyclientbacs
  | grg_paidbyclientchaps |  
  | grg_paidbyclientchapsname | grg_paidbyclientchaps
  | grg_partnercampaignid |  
  | grg_partnercampaignidname | grg_partnercampaignid
  | grg_partnerlandingpage |  
  | grg_partnershipacc2contact |  
  | grg_partnershipacc2contactname | grg_partnershipacc2contact
  | grg_partnershipacc2contactyominame | grg_partnershipacc2contact
  | grg_partnershipaccount2 |  
  | grg_partnershipaccount2name | grg_partnershipaccount2
  | grg_partnershipaccount2yominame | grg_partnershipaccount2
  | grg_partneshipaccount |  
  | grg_partneshipaccountname | grg_partneshipaccount
  | grg_partneshipaccountyominame | grg_partneshipaccount
  | grg_previouscompanyname |  
  | grg_primarypartnermanager |  
  | grg_primarypartnermanagername | grg_primarypartnermanager
  | grg_primarypartnermanageryominame | grg_primarypartnermanager
  | grg_product |  
  | grg_productclass |  
  | grg_productclassname | grg_productclass
  | grg_productname | grg_product
  | grg_referral |  
  | grg_referralname | grg_referral
  | grg_referringaccount |  
  | grg_referringaccountcontact |  
  | grg_referringaccountcontactname | grg_referringaccountcontact
  | grg_referringaccountcontactyominame | grg_referringaccountcontact
  | grg_referringaccountname | grg_referringaccount
  | grg_referringaccountyominame | grg_referringaccount
  | grg_referringuser |  
  | grg_referringusername | grg_referringuser
  | grg_referringuseryominame | grg_referringuser
  | grg_regulatedby |  
  | grg_relationshipnotes |  
  | grg_riskscore |  
  | grg_riskscoredate |  
  | grg_salesexecutiveid |  
  | grg_salesexecutiveidname | grg_salesexecutiveid
  | grg_salesexecutiveidyominame | grg_salesexecutiveid
  | grg_salesforceprimarykey |  
  | grg_secondaypartnermanager |  
  | grg_secondaypartnermanagername | grg_secondaypartnermanager
  | grg_secondaypartnermanageryominame | grg_secondaypartnermanager
  | grg_sendfundstofromcomplete |  
  | grg_sendfundstofromcompletename | grg_sendfundstofromcomplete
  | grg_servicelineid |  
  | grg_servicelineidname | grg_servicelineid
  | grg_servicelineoption |  
  | grg_servicelineoptionname | grg_servicelineoption
  | grg_servicingofficeid |  
  | grg_servicingofficeidname | grg_servicingofficeid
  | grg_signupprogressdate |  
  | grg_sortcode |  
  | grg_sourceoffunds |  
  | grg_sourceoffundscompleted |  
  | grg_sourceoffundscompletedname | grg_sourceoffundscompleted
  | grg_sourceoffundsname | grg_sourceoffunds
  | grg_sourceoffundsother |  
  | grg_spt_method |  
  | grg_spt_methodname | grg_spt_method
  | grg_spt_noofleadreferrals |  
  | grg_spt_numberofyears |  
  | grg_spt_paidonnoofyears |  
  | grg_spt_paidonnoofyearsname | grg_spt_paidonnoofyears
  | grg_spt_paidonreferrals |  
  | grg_spt_paidonreferralsname | grg_spt_paidonreferrals
  | grg_sptautoibpayment |  
  | grg_sptautoibpaymentname | grg_sptautoibpayment
  | grg_sptautopayment |  
  | grg_sptautopaymentname | grg_sptautopayment
  | grg_sptaveragetradesize |  
  | grg_sptaveragetradesizename | grg_sptaveragetradesize
  | grg_sptbankaddress1 |  
  | grg_sptbankaddress2 |  
  | grg_sptbankcity |  
  | grg_sptbankcountry |  
  | grg_sptbankcountryname | grg_sptbankcountry
  | grg_sptbankcounty |  
  | grg_sptbankzippostcode |  
  | grg_sptbeneficiarybank |  
  | grg_sptbeneficiaryname |  
  | grg_sptprofitturnover |  
  | grg_sptprofitturnovername | grg_sptprofitturnover
  | grg_staffcommissionpercentage |  
  | grg_stagingprimarykey |  
  | grg_subsourceid |  
  | grg_subsourceidname | grg_subsourceid
  | grg_subsourceother |  
  | grg_swift |  
  | grg_syncdate |  
  | grg_syncstatus |  
  | grg_syncstatusname | grg_syncstatus
  | grg_termsandconditionssigned |  
  | grg_termsandconditionssigneddate |  
  | grg_termsandconditionssignedname | grg_termsandconditionssigned
  | grg_termsandconditionsversion |  
  | grg_thirdpartyfunds |  
  | grg_thirdpartyfundsname | grg_thirdpartyfunds
  | grg_tniovationtoken |  
  | grg_tnjsonresponse |  
  | grg_tnsyncdate |  
  | grg_tnsyncstatus |  
  | grg_tnsyncstatusname | grg_tnsyncstatus
  | grg_tradingtenor |  
  | grg_trunarrativeaccountid |  
  | grg_trunarrativecallallowed |  
  | grg_trunarrativecallallowedname | grg_trunarrativecallallowed
  | grg_trunarrativecallrequired |  
  | grg_trunarrativecallrequiredname | grg_trunarrativecallrequired
  | grg_trunarrativeintegrationtoggle |  
  | grg_ttcaassessmentdate |  
  | grg_ttcaclient |  
  | grg_ttcaclientname | grg_ttcaclient
  | grg_value |  
  | grg_valuename | grg_value
  | grg_vmpercentage |  
  | grg_walletshare |  
  | grg_watchlistbox |  
  | grg_watchlistboxname | grg_watchlistbox
  | grg_webformintegrationtoggle |  
  | grg_webformipaddress |  
  | grg_webformrecordurl |  
  | grg_webformtrackingcode |  
  | grg_webformurlcounter |  
  | importsequencenumber |  
  | industrycode |  
  | industrycodename | industrycode
  | isprivate |  
  | isprivatename | isprivate
  | lastonholdtime |  
  | lastusedincampaign |  
  | marketcap |  
  | marketcap_base |  
  | marketingonly |  
  | marketingonlyname | marketingonly
  | masteraccountidname | masterid
  | masteraccountidyominame | masterid
  | masterid |  
  | merged |  
  | mergedname | merged
  | modifiedby |  
  | modifiedbyexternalparty |  
  | modifiedbyexternalpartyname | modifiedbyexternalparty
  | modifiedbyexternalpartyyominame | modifiedbyexternalparty
  | modifiedbyname | modifiedby
  | modifiedbyyominame | modifiedby
  | modifiedon |  
  | modifiedonbehalfby |  
  | modifiedonbehalfbyname | modifiedonbehalfby
  | modifiedonbehalfbyyominame | modifiedonbehalfby
  | name |  
  | numberofemployees |  
  | onholdtime |  
  | opendeals |  
  | opendeals_date |  
  | opendeals_state |  
  | openrevenue |  
  | openrevenue_base |  
  | openrevenue_date |  
  | openrevenue_state |  
  | originatingleadid |  
  | originatingleadidname | originatingleadid
  | originatingleadidyominame | originatingleadid
  | overriddencreatedon |  
  | ownerid |  
  | owneridname | ownerid
  | owneridtype | ownerid
  | owneridyominame | ownerid
  | ownershipcode |  
  | ownershipcodename | ownershipcode
  | owningbusinessunit |  
  | owningteam |  
  | owninguser |  
  | parentaccountid |  
  | parentaccountidname | parentaccountid
  | parentaccountidyominame | parentaccountid
  | participatesinworkflow |  
  | participatesinworkflowname | participatesinworkflow
  | paymenttermscode |  
  | paymenttermscodename | paymenttermscode
  | preferredappointmentdaycode |  
  | preferredappointmentdaycodename | preferredappointmentdaycode
  | preferredappointmenttimecode |  
  | preferredappointmenttimecodename | preferredappointmenttimecode
  | preferredcontactmethodcode |  
  | preferredcontactmethodcodename | preferredcontactmethodcode
  | preferredequipmentid |  
  | preferredequipmentidname | preferredequipmentid
  | preferredserviceid |  
  | preferredserviceidname | preferredserviceid
  | preferredsystemuserid |  
  | preferredsystemuseridname | preferredsystemuserid
  | preferredsystemuseridyominame | preferredsystemuserid
  | primarycontactid |  
  | primarycontactidname | primarycontactid
  | primarycontactidyominame | primarycontactid
  | primarysatoriid |  
  | primarytwitterid |  
  | processid |  
  | revenue |  
  | revenue_base |  
  | sharesoutstanding |  
  | shippingmethodcode |  
  | shippingmethodcodename | shippingmethodcode
  | sic |  
  | slaid |  
  | slainvokedid |  
  | slainvokedidname | slainvokedid
  | slaname | slaid
  | stageid |  
  | statecode |  
  | statecodename | statecode
  | statuscode |  
  | statuscodename | statuscode
  | stockexchange |  
  | teamsfollowed |  
  | telephone1 |  
  | telephone2 |  
  | telephone3 |  
  | territorycode |  
  | territorycodename | territorycode
  | territoryid |  
  | territoryidname | territoryid
  | tickersymbol |  
  | timespentbymeonemailandmeetings |  
  | timezoneruleversionnumber |  
  | transactioncurrencyid |  
  | transactioncurrencyidname | transactioncurrencyid
  | traversedpath |  
  | utcconversiontimezonecode |  
  | versionnumber |  
  | websiteurl |  
  | yominame |

**Comment by MarkMpn** [comment]
Do you know what the attribute `grg_grmaccountopeningdocument` is? There are some virtual attributes that refer to it, but it doesn't appear as an attribute in its own right.

**Comment by aylosx** [comment]
That makes sense, it is of the new type File and most probably that was the reason that the CrmSvcUtil was failing too
![image](https://user-images.githubusercontent.com/6900439/103903704-2486fa00-50f4-11eb-8e2b-f6949671a502.png)

the ...anchor is just a text attribute which i am using with a PCF control to upload the files into it.

**Comment by MarkMpn** [comment]
OK thanks, I'll take a look at why this isn't coming back in the metadata.

**Comment by aylosx** [comment]
Not sure if it helps but I also checked in the Metadata Browser plug-in and it doesn't come as an attribute there either. 

![image](https://user-images.githubusercontent.com/6900439/103905043-05896780-50f6-11eb-9886-2bede22cec09.png)

Let me know if you need anything else :-)

**Comment by aylosx** [comment]
Thank you for resolving this, works like a charm :-)
