### ISSUE TITLE
"Object reference not set to an instance of an object" if a column is not available in tables / subqueries

### ISSUE THREAD

**Issue by n0rthface** [MarkMpn/Sql4Cds#463]
Hi Mark,

Thank you very much for deploying another version full of great enhancements!
I just discovered a minor issue in v9.0 which I would like to point out to you.
When a column is not included in a table / view / subquery, instead of returning the missing column, I receive the all too common error message "Object reference not set to an instance of an object"

![image](https://github.com/MarkMpn/Sql4Cds/assets/14167302/d3dfd04b-fcd2-415b-ab88-9484e0b3322b)

Best regards
Hauke

**Comment by SiPurdy** [comment]
I wonder if this issue is the same as #462?
