### ISSUE TITLE
[Question] initiatingPluginExecutionContext.InitiatingPluginInfoProvider is null. Restricted API is not called by Microsoft publisher plugin.

### ISSUE THREAD

**Issue by sybaris** [MarkMpn/Sql4Cds#472]
Hi,

First thanks for our tools. They are very usefull.

Currently, the following fetchXml return me the error :

```
<fetch xmlns:generator='MarkMpn.SQL4CDS' top='10'>
  <entity name='solutionhistorydata'>
    <all-attributes />
  </entity>
</fetch>
```

"_initiatingPluginExecutionContext.InitiatingPluginInfoProvider is null. Restricted API is not called by Microsoft publisher plugin_".

Some month ago, the same fetchXML execute without problem. It seems that since my last attempt, Microsoft has restricted access to this table.

Do you know a way (including code development) to bypass this and get data on this table ?

Thanks for advance.
Regards
Sybaris

![image](https://github.com/MarkMpn/Sql4Cds/assets/11009997/b7777836-16ef-426a-a05a-5dfbc3bfec9e)

**Comment by MarkMpn** [comment]
No, but it appears there is now a new table `msdyn_solutionhistory` which contains similar data which you could use instead.

**Comment by sybaris** [comment]
Hi,

Thanks for the information...

Regards
Sybaris
