### ISSUE TITLE
Adding a column alias can screw up the values

### ISSUE THREAD

**Issue by trobblob** [MarkMpn/Sql4Cds#477]
They say a picture is worth a thousand words, and I'd rather not type that many (also I think this picture explains the problem pretty well):

![evidence](https://github.com/MarkMpn/Sql4Cds/assets/48190250/87062521-4361-4f77-a561-f1d324567884)

I suspect that this is a problem for those columns ending with "name" (e.g. territoryidname).

**Comment by JeffFahl** [comment]
I am seeing this issue as well and it is very much a concern since I use aliases often.
