### ISSUE TITLE
Can't delete entity records whose entity has a 1:N relationship to a virtual entity

### ISSUE THREAD

**Issue by tony-mykhaylovsky-va** [MarkMpn/Sql4Cds#478]
Hi Mark,

I have a custom entity that has a 1:N relationship with a virtual entity.

**When deleting the custom entity with a where clause:**
delete from ops_summary
where ops_name like 'ZZZ Summary %'

**error:**
Msg 10337, Level 16, State 1, Line 1
DeleteMultiple has not yet been implemented

I also checked the following:
1. Can delete multiple custom entity records in the UI (check boxes - unsure if DeleteMultiple runs or if its an individual Delete).
2. Created a power automate to delete a specific ops_summary record and it works
3. Checked the 1:N settings and behavior is set to Referential
4. The virtual entity that is N:1 to custom entity has Delete step as unimplemented (this is intended)
5. I can delete an OOB record like a contact just fine.

Thank you for considering this question.

Best,
Tony

**Comment by MarkMpn** [comment]
This looks the same as #469, please see the workaround there until this is fixed in the next release
