### ISSUE TITLE
Results view issue (left vs inner)?

### ISSUE THREAD

**Issue by chironh** [MarkMpn/Sql4Cds#479]
Pretty wierd behaviour I'm experiencing, which I cannot explain. 

Left join gives me 7xx records, but all of them were joined in the end.

`select account.accountid, account.inf_countryinvoiceaddressid, account.inf_countryinvoiceaddress, inf_country.inf_countryid
from account
left join inf_country ON account.inf_countryinvoiceaddress = inf_country.inf_name
where account.inf_accountstatus = 1
and account.inf_countryinvoiceaddressid is null
and account.inf_countryinvoiceaddress is not null`

![image](https://github.com/MarkMpn/Sql4Cds/assets/22192228/8f4065c1-36f3-4b80-a034-427d6b5fc5a6)

Inner join gives me 7 records, with strange red signs. The inner join should also give me 7xx results.

`select account.accountid, account.inf_countryinvoiceaddressid, account.inf_countryinvoiceaddress, inf_country.inf_countryid
from account
inner join inf_country ON account.inf_countryinvoiceaddress = inf_country.inf_name
where account.inf_accountstatus = 1
and account.inf_countryinvoiceaddressid is null
and account.inf_countryinvoiceaddress is not null`

![image](https://github.com/MarkMpn/Sql4Cds/assets/22192228/25a3c810-68b6-4f57-b804-7bbd7383f290)

Messages tab still shows me this: (713 rows affected)?

I've checked the fetchxml's behind the scenes and the only difference is inner vs outer.

Ran the same inner query in FetchXML Builder, and this gave me the expected 7xx results.

I'm using version 9.0.1.

**Comment by MarkMpn** [comment]
I’ve never seen anything like that before - can you reproduce it?

I wonder if it’s possible that some other tool running within XrmToolBox at the same time could have had some sort of effect on the grid control - can you try restarting XrmToolBox, open only SQL 4 CDS and run the query again?

**Comment by chironh** [comment]
Yes I can reproduce it.

I'll try reinstalling SQL4CDS and try again.

**Comment by chironh** [comment]
I have uninstalled the plugin, reinstalled the plugin, removed the roaming files as asked by the plugin, checked XrmToolbox (which is latest), .. still the issue persist somehow.

![image](https://github.com/MarkMpn/Sql4Cds/assets/22192228/f6e8cda2-e8bf-4409-a28c-16790ef70a3d)
![image](https://github.com/MarkMpn/Sql4Cds/assets/22192228/33dc10b4-c237-4ec7-8b31-58dc6025889d)
![image](https://github.com/MarkMpn/Sql4Cds/assets/22192228/c183bdd1-1cae-4cd9-998b-5b99215efd6d)

If you want me to test certain things, or to provide you with some kind of logs, let me know. Just trying to help you out by making this plugin even better, because this thing is freaking awesome :)

**Comment by MarkMpn** [comment]
Is there any way you can either get me access to this instance to try to reproduce it myself, or export a solution containing these entities and a CSV export of the records I can then import into my own instance for testing?

If you could create an application user with read access to the metadata and these entities and send the client ID and secret to sql4cds@markcarrington.dev that would be great.

**Comment by chironh** [comment]
I think I just found a possible cause:
As you can see I'm not joining on the ID of the records, but on a string field. If joining on the ID, which gives me in this case more of less the same amount of results, there is no difference between inner and left/outer.

Could this be the culprit?

**Comment by chironh** [comment]
Yeah, this could be it. I tested the same scenario on a different environment (other customer):

![image](https://github.com/MarkMpn/Sql4Cds/assets/22192228/0d169d26-b903-429d-8193-a7b1d02cb583)

**Comment by MarkMpn** [comment]
That's great, thanks for your help debugging this. I've managed to reproduce this now, I should be able to include a fix in the next update.
