### ISSUE TITLE
Feature Request: Provider Template Update/Insert Statements

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/Sql4Cds#487]
Allow for a similar feature as SSMS with being able to generate template statements for CRUD operations:

![image](https://github.com/MarkMpn/Sql4Cds/assets/9728423/da98ec51-45d8-4ba8-83df-e4e34adadd37)

Bonus points if you figure out how to include Copilot natural language to generate the Script.  (Like, a lot of Lots of bonus points)

**Comment by MarkMpn** [comment]
I'd got a prototype copilot version built a while ago but never figured out how to cover the costs of making the AI requests. I think I'd need to get users to set up their own [Azure] Open AI resources and enter a key in the configuration somewhere so SQL 4 CDS could use it and you handle your own billing. I'll see if I can dust that version off and get it ready for release.
