### ISSUE TITLE
Inner join with audit does not returns expected result...

### ISSUE THREAD

**Issue by sybaris** [MarkMpn/Sql4Cds#488]
Hi

The following query does not returns correct rows :

```
select count(*)
from systemuser 
inner join Audit on systemuserid = userid
where systemuserid='...'
```

![image](https://github.com/MarkMpn/Sql4Cds/assets/11009997/e5967b56-53db-4faf-9089-af2edd363e90)

I take the systemuserid of a user.
So I find 1 user in systemuser.
This user have 183 rows in audit table.
So when we are making an inner join between this 2 datasets, I except to have 183 rows.
Instead, we have 1234874 rows.
Note that 1234874 is also the number of rows of Audit table...

Regards
Sybaris

**Comment by MarkMpn** [comment]
Thanks for the details. It looks like the server is interpreting the inner joins as outer joins. With some more testing I've found some more attributes that it doesn't seem to support filtering on either, listing them here for my reference to fix shortly:

* `attributemask`
* `userid` & `callinguserid` (with `eq-userid` and `ne-userid` conditions)
* `objectidname`
