### ISSUE TITLE
[Feature Request] : Add metadata for RetrieveAvailableLanguages

### ISSUE THREAD

**Issue by sybaris** [MarkMpn/Sql4Cds#494]
Hi,

Is it possible to add in medata informations from RetrieveAvailableLanguages please ?

![image](https://github.com/MarkMpn/Sql4Cds/assets/11009997/eaaf142d-956d-421e-af9a-96450de403b8)

Info availiable using : https://xxx.api.crm4.dynamics.com/api/data/v9.2/RetrieveAvailableLanguages

Regards
Jean-Pierre

**Comment by MarkMpn** [comment]
I'd probably link this to #442 so you could do something like `SELECT LocaleId FROM RetrieveAvailableLanguages()` or `EXEC RetrieveAvailableLanguages`
