### ISSUE TITLE
Operand type clash: decimal is incompatible with decimal

### ISSUE THREAD

**Issue by TobiasKoller** [MarkMpn/Sql4Cds#527]
hi,

I'm trying to update data from an inner join like 

update new_myentity 
    set l.new_mycolumn1 = e.new_mycolumn1
from new_myentity l
    inner join new_myotherentity e 
    on l.new_myentityid = e.new_myentityid

this works perfectly (i updated 5 columns with no problem). But for 2 columns I'm not able to update the data like this.
The error:

Operand type clash: decimal is incompatible with decimal

any idea how to handle this?

Best Regards
Tobias

btw: this is the most important and most used tool for me. i don't know how I could work in CE before ;-)

**Comment by MarkMpn** [comment]
Can you share the metadata for the affected columns please?
