### ISSUE TITLE
10337 - Invalid Scope Value

### ISSUE THREAD

**Issue by sdygert1** [MarkMpn/Sql4Cds#553]
Try to change the owner of my call back registration and getting the following error:

```sql
UPDATE [dbo].[callbackregistration]
SET [ownerid] = '8068009F-CB68-ED11-9560-000D3A5C4369'
WHERE [callbackregistrationid] = '2E3015AF-3B5C-EE11-BE6F-00224805CB5E'
```

```
  ___  ___  _      _ _     ___ ___  ___ 
 / __|/ _ \| |    | | |   / __|   \/ __|
 \__ \ (_) | |__  |_  _| | (__| |) \__ \
 |___/\__\_\____|   |_|   \___|___/|___/  v9.3.0

 INSERT/UPDATE/DELETE commands are implemented by SQL 4 CDS
 and not supported by Microsoft
 https://markcarrington.dev/sql-4-cds/

Updating 1 Callback Registration...
Msg 10337, Level 16, State 1, Line 1
Invalid scope value

Completion time: 2024-09-19T11:15:42.1974047-04:00
```

**Comment by MarkMpn** [comment]
This error is coming from some server-side validation which requires you to set the value of the scope field at the same time when you update the owner.

You can work around this by specifying this field in your update statement, but you then get a series of similar messages referencing other fields. This ends up with one referencing the url field. Unfortunately there appears to be no way to retrieve the existing value of this field, so I haven’t found a safe way to perform this update without losing the url.

As far as I can see, there isn’t a way for SQL 4 CDS to work around this limitation. Presumably Microsoft have imposed this restriction to prevent you accidentally breaking your flows by directly editing the tables and so you should make any changes in the Power Automate maker portal to ensure this table is updated consistently.
