### ISSUE TITLE
Calling from FXB fails

### ISSUE THREAD

**Issue by rappen** [MarkMpn/Sql4Cds#556]
Calling you with:
```csharp
OnOutgoingMessage(this, new MessageBusEventArgs("SQL 4 CDS", true) { TargetArgument = dockControlBuilder.GetFetchString(true, true) });
```
`dockControlBuilder.GetFetchString` returns the Fetch XML as a string.

But I got:
```
Error Time: 2024-10-04 22:16:21.130
System.TypeInitializationException
The type initializer for 'MarkMpn.Sql4Cds.Engine.ExecutionPlan.MetadataQueryNode' threw an exception.
MarkMpn.Sql4Cds.Engine
at MarkMpn.Sql4Cds.Engine.ExecutionPlan.MetadataQueryNode..ctor()
   at MarkMpn.Sql4Cds.Engine.MetaMetadataCache..cctor()
```
and the the whole XTB crashes and closed.

I'm unknow about why I get this issue...

---
- Deployment: Online
- DB Version: 9.2.24091.196
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.10.67
- Tool Version: 9.3.0.0

**Comment by MarkMpn** [comment]
It sounds like it can’t find an expected property in the metadata classes. Can you please try with the latest version of XTB and the connection controls?
