### ISSUE TITLE
[Bug?] Table-valued function execution failed

### ISSUE THREAD

**Issue by hiroyuki0415** [MarkMpn/Sql4Cds#559]
```sql
SELECT *
FROM searchstatus()
```

When I run this SQL I get the below error:
```
Expected non-empty Guid.

Trace log: 
[Microsoft.CDS.RelevanceSearch.Plugins: Microsoft.CDS.RelevanceSearch.Plugins.StatusPlugin]
[32daf801-a29c-ec11-b400-000d3acf6a11: CustomApi 'searchstatus' implementation]
```

**Comment by MarkMpn** [comment]
This appears to be an error in the plugin which occurs if you call the message directly without SQL 4 CDS. If this is resolved this should start working without any change to SQL 4 CDS.
