### ISSUE TITLE
Formatted values support

### ISSUE THREAD

**Issue by macco3k** [MarkMpn/Sql4Cds#570]
The standard sdk allows to retrieve formatted values next to the raw values, e.g. for enums (choices). Is this supported in sql4cds?

**Comment by MarkMpn** [comment]
Yes, they are available in the corresponding `name` field. For example, if your query to retrieve the choice values looks like:

```sql
SELECT new_choicevalue
FROM   account
```

you can add an extra column to get the formatted value:

```sql
SELECT new_choicevalue,
       new_choicevaluename
FROM   account
```

**Comment by macco3k** [comment]
Thanks for the quick reply. However, I could not find anything about this in the docs. Maybe good to mention that there as well? I can help with that with a pr if needed.

**Comment by MarkMpn** [comment]
I've added this to the [wiki](https://github.com/MarkMpn/Sql4Cds/wiki/Data-Types#select) now
