### ISSUE TITLE
[Bug?] (V9.4.0) Bulk insert error

### ISSUE THREAD

**Issue by edgeerrol87** [MarkMpn/Sql4Cds#575]
I'm trying to insert 30k records into Dataverse but when running the query in XrmToolbox I keep getting errors.

```sql 
INSERT INTO contact (lastname, nickname) VALUES
('Imported 00001', 'Test-Demo'),
('Imported 00002', 'Test-Demo'),
('Imported 00003', 'Test-Demo'),
.
.
.
('Imported 14460', 'Test-Demo'),
.
.
.
('Imported 29999', 'Test-Demo'),
('Imported 30000', 'Test-Demo');
```

Record inserting over 30k
![2024-11-06_23-13-14](https://github.com/user-attachments/assets/2e1bef14-db56-4fad-998b-c94f9db76898)

My setting:
![2024-11-06_23-37-53](https://github.com/user-attachments/assets/540beb4e-4aa8-4ed8-a402-966b88d9612b)

Error:
```
206 Contacts inserted
Msg 0, Level 1, State 1

Msg 10337, Level 16, State 1, Line 1
The request channel timed out while waiting for a reply after 00:01:59.9531245. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.

Msg 10337, Level 16, State 1, Line 1
The request channel timed out while waiting for a reply after 00:01:59.8593732. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.


The HTTP request to 'https://xxxxx.crmx.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.49.11611' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
The operation has timed out
The HTTP request to 'https://xxxxx.crmx.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.49.11611' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
The operation has timed out
See the Execution Plan tab for details of where this error occurred

Completion time: 2024-11-06T23:14:37.9202181+07:00
```

**There are duplicate records in the imported data, which I discovered after reporting the issue:**
![2024-11-07_00-08-12](https://github.com/user-attachments/assets/d6edad4a-4f90-4d0a-9b29-b21f0abea65d)

- XrmToolBox Version: 1.2024.9.69
- Microsoft Dataverse - 9.2.24102.172
- SQL 4 CDS - 9.4.0.0
- Nov 06 2024 22:01:35
- Copyright © 2020 - 2024 Mark Carrington

**Comment by MarkMpn** [comment]
It seems if an error occurs while processing a batch, it can try to process that same batch again a second time which leads to the duplicate records and incorrect count shown in the status bar - I should be able to get a fix out for this shortly.

The original source of the error is the timeout - to avoid this you will likely need to reduce the batch size from 600, and/or reduce the number of concurrent requests.
