### ISSUE TITLE
No documentation for MarkMpn.Sql4Cds.Engine.FetchXml NuGet

### ISSUE THREAD

**Issue by Marko97IT** [MarkMpn/Sql4Cds#588]
Hi,
I am trying to convert a SQL query to FetchXML and I found this NuGet library called `MarkMpn.Sql4Cds.Engine.FetchXml` however there is no documentation on how to use it.

https://www.nuget.org/packages/MarkMpn.Sql4Cds.Engine.FetchXml

**Comment by MarkMpn** [comment]
This package performs FetchXML to SQL conversion, not the other way around. To convert SQL to FetchXML you'll need to use the main MarkMpn.Sql4Cds.Engine package.

As many SQL queries are too complex to be represented as a single FetchXML query there is no method to do a simple conversion. However, you can get the engine to produce an execution plan for the SQL query and examine it to find any of the FetchXML queries it is going to use.

```csharp
// Set up the IOrganizationService
var svc = new ServiceClient("connectionstring");

// Create the SQL 4 CDS engine
using var con = new Sql4CdsConnection(svc);
using var cmd = con.CreateCommand();

// Specify the query to convert
cmd.CommandText = "SELECT name FROM account";

// Generate the execution plan(s) for the query
var plans = cmd.GeneratePlan(false);

// Find any FetchXML nodes in the execution plan
foreach (var plan in plans)
{
  FindFetchXml(plan);
}

void FindFetchXml(IExecutionPlanNode node)
{
  // Recurse through the source nodes of the execution plan
  foreach (var child in node.GetSources())
    FindFetchXml(child);

  if (node is IFetchXmlExecutionPlanNode fetch)
  {
    // TODO: Do something with the fetch.FetchXmlString
  }
}
```

**Comment by Marko97IT** [comment]
To semplify:

`private void ConvertSQLToFetchXMLQuery(string sqlQuery)
{
    using var sql4Cds = new Sql4CdsConnection(_serviceClient);
    sql4Cds.UseTDSEndpoint = false;

    using var cmd = sql4Cds.CreateCommand();
    cmd.CommandText = sqlQuery;

    var plans = cmd.GeneratePlan(false);

    foreach (var plan in plans)
    {
        FindFetchXml(plan);
    }
}

private void FindFetchXml(IExecutionPlanNode node)
{
    foreach (var child in node.GetSources())
    {
        FindFetchXml(child);
    }

    if (node is IFetchXmlExecutionPlanNode fetch)
    {
        var fetchXmlQuery = fetch.FetchXmlString;

        // TODO: ...
    }
}`

Missing `UseTDSEndpoint` to force FetchXML generation even for simple queries. The rest works fine.
