### ISSUE TITLE
Money attributes being rounded to nearest whole number

### ISSUE THREAD

**Issue by crusselllike10** [MarkMpn/Sql4Cds#589]
Attributes of type money are being rounded to the nearest whole number in query results.

I am using the latest version 9.4.1

**Comment by MarkMpn** [comment]
I can't reproduce this:

![image](https://github.com/user-attachments/assets/4890fb43-28b6-417a-9329-461ef3c4101c)

![image](https://github.com/user-attachments/assets/3464fd58-92e9-4ebb-ac8d-0db2fb835500)

Is there any more information you can give about your query, data and/or environment that might help?

**Comment by crusselllike10** [comment]
Sorry, I forget to mention I am using Azure Data Studio 1.50.0.

If I connect directly to the TDS endpoint in ADS and query the revenue attribute from account it shows fractional values, but when I do the same query with Sql4Cds they are rounded.
