### ISSUE TITLE
[BUG] Truncation-Exception when trying to update address1_country in account-table

### ISSUE THREAD

**Issue by TobiasKoller** [MarkMpn/Sql4Cds#604]
hi,

I'm trying to update the address1_country field in an account.
SQL-Statement: 

```sql
update account set address1_country='DEUTSCHLAND' where accountid='YOUR_GUID'
```

When I execute this I get this error:

```
Msg 2628, Level 16, State 1, Line 4
String or binary data would be truncated in table 'account', column 'address1_country'. Truncated value: 'DEUTSCHLAN'.

See the Execution Plan tab for details of where this error occurred
```

The addess1_country field has a length of 80 char.
I can update it everywhere else (fetch() in javascript, directly on the form..)..
SQL4CDS is the only tool that shows me this truncation-error.

**Comment by MarkMpn** [comment]
I haven’t been able to replicate this, can you please try updating to v9.5 and let me know if this still occurs?
