### ISSUE TITLE
[BUG] Error "Value cannot be null" when using variables

### ISSUE THREAD

**Issue by hiroyuki0415** [MarkMpn/Sql4Cds#605]
```sql
DECLARE @businessunitid AS UNIQUEIDENTIFIER = '72a2eae0-6da2-474e-b97b-158d0042d4b4';

SELECT b.businessunitid
FROM   businessunit AS b
WHERE  b.businessunitid IN (@businessunitid);
```
When I run this SQL, I get the below error:
```
Value cannot be null.
Parameter name:key
```

### Environment
 - SQL 4 CDS edition: XrmToolBox
 - Results of `SELECT @@VERSION`: 
```
Microsoft Dataverse - 9.2.24111.198
	SQL 4 CDS - 9.4.1.0
	11 11 2024 12:05:16
```

**Comment by MarkMpn** [comment]
This will be fixed in the next update, but seems to only affect an `IN` query with a single value - if you rewrite this as an `=` condition instead, or add more values to make it worthwhile using `IN` it should work as expected.
