### ISSUE TITLE
SQL 4 CDS Tools Service component exited unexpectedly (v9.5.0)

### ISSUE THREAD

**Issue by txh57** [MarkMpn/Sql4Cds#614]
I'm facing an error after upgrading the Azure Data Studio extension from 9.4.1 to 9.5.0 and reloading the app.
![image](https://github.com/user-attachments/assets/78c779bb-7fee-4e37-a28e-2643005e591e)

The Terminal output shows an error too.
![image](https://github.com/user-attachments/assets/2768bc26-7006-4676-9179-276163a24488)

I tried to uninstall and reinstall the extension but with no success.
This happens on Windows 10 and Windows 11 machines. My current version of the Azure Data Studio is 1.50.0.
![image](https://github.com/user-attachments/assets/7bc169e7-1d8c-4dd1-939c-40be2e3c7b87)

Is there anything I can do to narrow down the cause of the error?

**Comment by MarkMpn** [comment]
Can you check you have .NET 8 installed?

```
dotnet --list-runtimes
```

needs to include a `Microsoft.NETCore.App 8.x.x` line

**Comment by MarkMpn** [comment]
I think the latest build is missing the key files, I'll get a new build out shortly.

**Comment by txh57** [comment]
Version 9.5.1 fixed the issue.
Thanks for the quick update and a big compliment for the great tool.
