### ISSUE TITLE
[suggestion] auto-save sql tabs

### ISSUE THREAD

**Issue by malam-dev** [MarkMpn/Sql4Cds#67]
I would find it helpful if the tabs worked similar to the way Notepad++ does, keeping the SQL on the tabs between sessions, even if they were not explicitly saved / re-saved. Would help me not worry about computer restarts or app updates / restarts, etc.

**Comment by MarkMpn** [comment]
I like this idea, but I'm close to a v5 release now so I'll leave this for a later release. It will need some more consideration on how this will work with connecting those tabs to Dataverse instances once they are re-opened
