### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by tgiard2020** [MarkMpn/Sql4Cds#7]
I am trying to delete a bunch of records via the "SQL 4 CDS" tool.  Unfortunately, every time I try to delete these records, I receive the following error after 2 minutes: "The request channel timed out while waiting for a reply after 00:01:59.9937153. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout."
I know it is possible to change the "Service Timeout" field when connecting to an environment via the "Connection Wizard", but this is not an option for me.  I have to connect via the SDK Login Control due to multi-factor authentication.

How can I fix this so the request does not keep timing out?
Thanks!

**Comment by MarkMpn** [comment]
If you’re trying to delete multiple records, try reducing the batch size. Click the Settings button to open this screen:

![](https://markcarrington.dev/wp-content/uploads/2020/03/SQL-4-CDS-Settings.png)

Try reducing the “Update and delete records in batches of” setting right down to 1, then CDS will have up to 2 minutes for each record you’re trying to delete.
