### ISSUE TITLE
Could not load file or assembly MarkMpn.Sql4Cds.Engine, Version=2.1.0.0

### ISSUE THREAD

**Issue by LinnZawWin** [MarkMpn/Sql4Cds#8]
The Sql4Cds tool is not loading any more after the last update to 2.1.0.0 due to missing referenced assembly MarkMpn.Sql4Cds.Engine, Version=2.1.0.0.
Uninstalled and reinstalled the tool from the Tool Library but the same error occurs.

![image](https://user-images.githubusercontent.com/14156926/82770035-28c71580-9e8b-11ea-82bd-e4901422cd28.png)

**Comment by MarkMpn** [comment]
Thanks, I've just pushed 2.1.1 to fix this, it should appear in the tool library shortly.
