### ISSUE TITLE
What happened to CreateLookup and CreatePrimaryKeyLookup?

### ISSUE THREAD

**Issue by malam-dev** [MarkMpn/Sql4Cds#85]
I used to be able to use those functions to add records to marketing lists, like with

```
insert into listmember (entityid, listid)
select
createprimarykeylookup('contact', contactid)
,createlookup('list','00000000-0000-0000-0000-000000000000')
from contact c
where ...
```

but now I can't use those since the functions don't exist. Is there a new or suggested way to do this now?

**Comment by MarkMpn** [comment]
These custom functions are no longer required and lookup values can be inserted/updated by using the corresponding ___type field, e.g.

```sql
INSERT INTO contact (firstname, lastname, parentcustomerid, parentcustomeridtype)
VALUES ('Mark', 'Carrington', '<guid>', 'account')
```

This keeps the XrmToolBox version of SQL 4 CDS consistent with the SSMS plugin version, which didn't support the `CREATELOOKUP` function.

However, I've identified a bug with using this with `listmember` and other intersect tables, which will be fixed shortly.
