### ISSUE TITLE
Error updating values to null

### ISSUE THREAD

**Issue by MarkMpn** [MarkMpn/Sql4Cds#89]
```sql
UPDATE account SET primarycontactid = NULL WHERE ...
```

**Comment by richwaring** [comment]
Hey Mark, hope you're well.

Is there a way I can tell if this issue is in a release?

It's just blocking me from fixing a production issue that will bite us in a couple of weeks time if we don't fix it.
As with so many things (!) Sql4Cds is the quickest, easiest way to sort it out.

Cheers,

Rich

**Comment by MarkMpn** [comment]
It's not yet, hopefully over the weekend!
