### ISSUE TITLE
Any chance of supporting global option sets and translations?

### ISSUE THREAD

**Issue by marcscheuner-bfh** [MarkMpn/Sql4Cds#9]
Any chance that SQL-4-CDS might eventually support reading (and possibly updating) global option sets, and the translations for those? That would really be a great feature !

**Comment by MarkMpn** [comment]
Never say never, but this would be a big change to the core engine as metadata including optionsets aren't accessible via FetchXML. My preferred solution would be to use a virtual entity which exposes the optionsets as entities, then they would be queryable through this tool.

**Comment by marcscheuner-bfh** [comment]
Hi Mark - do you have some sample code showing how to surface an option set as a virtual entity? That would be a smart way to do it - just don't have much experience with those just yet ....

**Comment by MarkMpn** [comment]
You can query these now in 3.0.0 using the globaloptionset table. Please let me know if you hit any problems with it!
