### ISSUE TITLE
La somme des valeurs FillWeight des colonnes ne peut pas dépasser 65535.

### ISSUE THREAD

**Issue by sybaris** [MarkMpn/Sql4Cds#97]
Hi,

SQL4CDS does not work anymore on my environment.
The error I have is "_La somme des valeurs FillWeight des colonnes ne peut pas dépasser 65535._"

![image](https://user-images.githubusercontent.com/11009997/117771037-f8ac8a00-b235-11eb-9519-6320bf098104.png)

Note that the table incident in your environment have many columns. Some weeks ago, I was able to get results from the same table. I don't know if the problem is from an update of Sql4Cds or because we have added some new columns...

Regards
Sybaris

**Comment by MarkMpn** [comment]
Can you check what version of SQL 4 CDS you are running please? I believe this was fixed in 5.1.0

**Comment by sybaris** [comment]
Exact, you are right, I was with 5.0.0, and the update to 5.1 has solved the issue.
Thanks you a lot.
