### ISSUE TITLE
Not movable query result window

### ISSUE THREAD

**Issue by rafek1241** [MarkMpn/Sql4Cds#99]
Bug existing only when more than one query is executed at the same time. First query result has one row which I can't see because of this issue. Second query does not have any row.

![image](https://user-images.githubusercontent.com/9272027/121664731-132d8980-caa8-11eb-94cb-64d9b9ef8a7f.png)

**Comment by MarkMpn** [comment]
Thanks, I hadn't accounted for the scrollbar in the height calculation for the first grid. This will be fixed in the next update.
